### ISSUE TITLE
Add tab complete support with the openai provider (non-ollama)

### ISSUE THREAD

**Issue by max-wittig** [continuedev/continue#1092]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

This is a continuation from this comment: https://github.com/continuedev/continue/pull/758#issuecomment-1949242717

Thanks for building continue.dev! It would be cool, if we could also use the tab autocomplete functionality with an openai provider.

e.g.

```json
 "tabAutocompleteModel": {
    {
      "title": "Starcoder",
      "provider": "openai",
      "model": "starcoder2",
      "apiKey": "some-api-key",
      "apiBase": "https://myapibase.example.com/llm/v1"
    }
}
```

Right now, this will just cause continue.dev to send empty string to our litellm backend.

/cc @fh1ch @ercanucan @bufferoverflow

### Solution

Add support for openai provider in tab autocomplete functionality

**Comment by sestinj** [comment]
@max-wittig Thanks for bringing this up! I ran a few tests using Fireworks AI's OpenAI-compatible endpoint (https://continue.dev/docs/walkthroughs/tab-autocomplete#setting-up-with-starcoder-2-7b-recommended), but unfortunately haven't gotten a clean reproduction of the problem yet. We had intended for this to be working, so I'm relabeling it as a bug.

Are there any more details you might be able to share about what is happening? A few items that might be helpful:
- Continue extension version (e.g. 0.8.23)
- Full config.json (not including any secrets or private API endpoints)
- Continue LLM prompt logs: Click the "Output" tab next to "Terminal" in VS Code, then in the dropdown on the right select "Continue - LLM Prompts/Completions". This panel will show the exact prompts sent to the LLM and the completions received, and is often useful for debugging.
- Request body from the LiteLLM server
- Any additional information from the LiteLLM side

**Comment by max-wittig** [comment]
Working now! We just had some issue with LiteLLM! Thanks!

**Comment by dimidagd** [comment]
Not working for me, @max-wittig can you share more details?

**Comment by max-wittig** [comment]
@dimidagd Sure, I configured continue.dev like this:

```json
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete Model",
    "model": "starcoder2-3b",
    "provider": "openai",
    "apiKey": "your-api-key",
    "apiBase": "https://your-api-base/llm/v1"
  }
```

---

Litellm config

```yml
  - model_name: starcoder2-3b
    litellm_params:
      api_base: https://your-vllm-node/v1
      api_key: THIS_IS_UNUSED
      model: text-completion-openai/starcoder2-3b
      stream_timeout: 5
    model_info:
      mode: completion
      metadata: >
        StarCoder2 trained with The Stack v2 dataset. More information:
        https://huggingface.co/bigcode/starcoder2-3b
```
