### ISSUE TITLE
json may not be the best config format for multi-line prompts, how about config with YAML ?

### ISSUE THREAD

**Issue by aijit** [continuedev/continue#1317]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

current `/test` in `config.json` looks like:

```json
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ]
```

### Solution

`/test` with `config.yaml` can be like:

```yaml
  customCommands:
      name: test
      prompt: |
        {{{ input }}}
        Write a comprehensive set of unit tests for the selected code. 
        It should setup, run tests that check for correctness including important edge cases, and teardown.
        Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.
      description: Write unit tests for highlighted code
```
