### ISSUE TITLE
Support for right-to-left (RTL) texts

### ISSUE THREAD

**Issue by NabiKAZ** [continuedev/continue#2767]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Please add a possibility to chat texts and their replies if they are, for example, Persian(Farsi) or Arabic. Display them right to left (RTL).

### Solution

Maybe like this:
```css
.thread-message {
    direction: rtl !important;
    text-align: right !important;
}
```
