### ISSUE TITLE
Continue doesn't allow setting penalty parameters for Ollama provider

### ISSUE THREAD

**Issue by 0rzech** [continuedev/continue#3053]
### Before submitting your bug report

- [X] I believe this is a bug.
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue version: v0.8.58
```

### Description

Ollama allows setting `repeat_penalty`, `presence_penalty` and `frequency_penalty` when doing API calls _[1]_, neither of which can be used with it within Continue _[2]_.

Also, available Ollama options _[3]_ seem to be modelled after Model File _[4]_ (which AFAIU is used to create models _[5]_, not to make API calls), rather than API options from _[1]_.

This is important, because Ollama sets `repeat_penalty` to `1.1` by default and instruction-tuned models should not penalize repetitions _[6][7]_. So to use these with Continue and Ollama, one has to create custom models just to hardcode this parameter.

1. https://github.com/ollama/ollama/blob/a820d2b2673f7f8035e3a2a6f93c83af465f841c/docs/api.md#request-7
2. https://github.com/continuedev/continue/blob/2c597764cac076a6342625273e43f203b74f2da6/core/llm/llms/Ollama.ts#L184-L197
3. https://github.com/continuedev/continue/blob/2c597764cac076a6342625273e43f203b74f2da6/core/llm/llms/Ollama.ts#L15-L36
4. https://github.com/ollama/ollama/blob/a820d2b2673f7f8035e3a2a6f93c83af465f841c/docs/modelfile.md#valid-parameters-and-values
5. https://github.com/ollama/ollama/blob/a820d2b2673f7f8035e3a2a6f93c83af465f841c/docs/modelfile.md#ollama-model-file
6. https://huggingface.co/google/gemma-2-2b-it-GGUF#gemma-model-card
7. https://huggingface.co/google/gemma-7b-it/discussions/38#65d7b14adb51f7c160769fa1

**Comment by Anisotropic** [comment]
Bump. Trying to use the newest QwQ and get a constant loop. Was unable to pass repeat_penalty to ollama host

**Comment by 0rzech** [comment]
Alright, here are the things I've learned in the meantime:
* [config.json](https://github.com/continuedev/continue/blob/8b418165d9d4b67ad14e619c6b8cf33a38efc6ae/docs/docs/json-reference.md) is going to be replaced with [config.yaml](https://github.com/continuedev/continue/blob/8b418165d9d4b67ad14e619c6b8cf33a38efc6ae/docs/docs/reference.md), so it's better to make a switch
* one can pass [ollama params](https://github.com/ollama/ollama/blob/ecf14a220f852528bae860ec09b52590f06e6744/docs/api.md) directly, for example:
  ```yaml
  models:
    - name: Some model
      provider: ollama
      model: some-model
      requestOptions:
        extraBodyProperties:
          options:
            repeat_penalty: 1
            presence_penalty: 1
            frequency_penalty: 1
            use_mmap: false
          keep_alive: 60m
  ```
* `requestOptions.extraBodyProperties.options` completely overwrite whatever can be set in `defaultCompletionOptions`
