### ISSUE TITLE
How to set up Brave Search and other reference servers as MCP model context protocol servers?

### ISSUE THREAD

**Issue by joewinke** [continuedev/continue#3544]
### Validations

- [X] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Continue.dev blog article highlights Brave specifically as a possible MCP server. Continue docs mention @web as a MCP server but provide no details how to set up.

### Solution

Instructions with example of Continue config.json showing Brave set up as MCP, as well as other reference servers listed on the MCP github repo: https://github.com/modelcontextprotocol/servers

**Comment by prd-tuong-nguyen** [comment]
@joewinke have you resolved problem?

**Comment by jtgsystems** [comment]
does anyone have some sort of plugin to get all 
MCPS at once?

**Comment by RomneyDa** [comment]
Hello!

Here is the canonical configuration approach with stdio

```yaml
  mcpServers:
    - name: Brave Search
      command: npx
      args:
        - "-y"
        - "@brave/brave-search-mcp-server"
        - "--transport"
        - "stdio"
      env:
        BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
```

**Comment by RomneyDa** [comment]
Other approaches

stdio via Docker

```yaml
  mcpServers:
    - name: Brave Search
      command: docker
      args:
        - "run"
        - "-i"
        - "--rm"
        - "-e"
        - "BRAVE_API_KEY"
        - "docker.io/mcp/brave-search"
      env:
        BRAVE_API_KEY: <API_KEY>
```

  streamable-http (remote HTTP server)

  First start the server separately:
  BRAVE_API_KEY=your_key npx @brave/brave-search-mcp-server --transport http --port 8000

  Then in config.yaml:
```yaml
  mcpServers:
    - name: Brave Search
      type: streamable-http
      url: http://localhost:8000/mcp
```
  sse (remote SSE server)

  Same remote server as above, but using SSE transport:
```yaml
  mcpServers:
    - name: Brave Search
      type: sse
      url: http://localhost:8000/sse
```
