### ISSUE TITLE
Azure Foundry models don't work (Mistral Codestral 2501 with Azure)

### ISSUE THREAD

**Issue by BastinFlorian** [continuedev/continue#3735]
### Issue Category

Undocumented feature or missing documentation

### Affected Documentation Page URL

https://docs.continue.dev/customize/model-providers/azure

### Issue Description

Using Codestral 2501 available in the Azure Hub through **Azure Foundry** or Azure ML products have a **different** target URI that **OpenAI Azure** models. 

Azure Open AI Target URI:
`https://just-an-example.openai.azure.com/openai/deployments/gpt-4o-july/chat/completions?api-version=2023-03-15-preview
`
Foundry Codestral URL example (same process for AzureML deployed models): 
`https://just-an-example.openai.azure.com/chat/completions?api-version=2023-03-15-preview
`

The difference is just : `openai/deployments/gpt-4o-july`

How to configure such models ? 
Can you please update the Codestral documentation thats seems to be lights/wrong for Autocomplete Codestral in Azure ? 

Adding this feature allows both Azure Foundry and Azure ML models to be deployed with continue dev because the URI are the same for both products (I know azure is messy). 

RESOLUTION: just add a new value for ApiType = 'foundry' to set the goold URI.

Version: 0.8.66 
IDE: VS Code

Thank you,

**Comment by Patrick-Erichsen** [comment]
Discord thread that this issue began in: https://discord.com/channels/1108621136150929458/1328759921512288316

**Comment by George-Const** [comment]
Same for deepseek-R1 in azure foundry.

**Comment by BastinFlorian** [comment]
Can you provide an URI exemple for DeepSeek ? Is it in the same format that the codestral one ? 
If yes, adding this feature could be very helpful.

**Comment by George-Const** [comment]
> Can you provide an URI exemple for DeepSeek ? Is it in the same format that the codestral one ? If yes, adding this feature could be very helpful.

for deepseek deployments, following urls are provided: 

  Target URI: 
  https://<deployment-name-here>.eastus.models.ai.azure.com
  
  API Routes
  
      Azure AI model inference: Chat Completion
      https://<deployment-name-here>.eastus.models.ai.azure.com/chat/completions
  
      DeepSeek-R1: Chat Completion
      https://<deployment-name-here>.eastus.models.ai.azure.com/v1/chat/completions

**Comment by Patrick-Erichsen** [comment]
Fix here: https://github.com/continuedev/continue/pull/4027

@BastinFlorian @George-Const - mind sharing your configs, with sensitive info removed? I know we had some mixups with the `apiType` and `provider` fields for Azure in the past, so want to make sure I'm not breaking any existing configs with that PR.

**Comment by BastinFlorian** [comment]
> > Fix here: [#4027](https://github.com/continuedev/continue/pull/4027)
> > [@BastinFlorian](https://github.com/BastinFlorian) [@George-Const](https://github.com/George-Const) - mind sharing your configs, with sensitive info removed? I know we had some mixups with the `apiType` and `provider` fields for Azure in the past, so want to make sure I'm not breaking any existing configs with that PR.
> 
> ![Image](https://github.com/user-attachments/assets/d9fb1111-187f-41a1-b74b-701bc0a05347) Model deployment rounting: https://learn.microsoft.com/en-us/azure/ai-foundry/model-inference/concepts/endpoints?tabs=python Hi, Patrick. This picture shows my deployment information, and the link explains model deployment routing. I hope it helps.

You have it one the [discord dicussion](https://discord.com/channels/1108621136150929458/1328759921512288316)

**Comment by Patrick-Erichsen** [comment]
Although @BastinFlorian , to your original question regarding Codestral w/ Azure, we're still awaiting a reply as to whether or not this is possible. The Azure docs seem to imply that Codestral can only be used for Chat: https://learn.microsoft.com/en-us/azure/ai-studio/how-to/deploy-models-mistral-codestral?pivots=programming-language-python

If this is indeed the case we'll update the docs to make it clear that Codestral can't be used for Autocomplete with Azure.

**Comment by fuglede** [comment]
I always wanted to play with Codestral for completetion, so following along on the side on this one, and while waiting for the PR to be completed, I had just manually patched the
```
    if (this.apiType === "azure") {
      return new URL(
        `openai/deployments/${this.deployment}/${endpoint}?api-version=${this.apiVersion}`,
        this.apiBase,
      );
    }
```
issue in the built extension, i.e. `~/.vscode/extensions/continue.continue-0.8.68-linux-x64/out/extension.js`.

And here, that was enough to get completions out of it in VS Code, so it looks like it is at least possible, but maybe not intended? The quality did strike me as surprisingly poor; infinite repetitions being common for instance.

**Comment by grosjeang** [comment]
> Although [@BastinFlorian](https://github.com/BastinFlorian) , to your original question regarding Codestral w/ Azure, we're still awaiting a reply as to whether or not this is possible. The Azure docs seem to imply that Codestral can only be used for Chat: https://learn.microsoft.com/en-us/azure/ai-studio/how-to/deploy-models-mistral-codestral?pivots=programming-language-python
> 
> If this is indeed the case we'll update the docs to make it clear that Codestral can't be used for Autocomplete with Azure.

In Azure AI Foundry, in my Codestral deployment details, I have 3 API routes including one route for FIM. When sending a post request to that route with a prompt and a suffix, it returns the code completion needed for Autocomplete. So using Codestral with Azure should be possible for Autocomplete. I don't know how API calls are made in Continue.dev for Azure AI Foundry models but I am not sure the `azure-ai-inference` package includes an easy way to do FIM for now.

**Comment by 2mas** [comment]
I got the code completions (and chat) working by deploying the Codestral model in Machine Learning studio (Foundry deployment + endpoint didn't work) and by using the provider: "mistral" in the model config

```
      "provider": "mistral",
      "apiKey": "",
      "deployment": "x",
      "apiBase": "https://x.models.ai.azure.com/v1",
      "model": "Codestral-2501",
      "title": "Codestral-2501"
```

**Comment by ulo** [comment]
The documentation on using Azure APIs is really rather outdated and it took me quite some try and error to properly configure Continue.

This is my config to get Chat + Autocompletion working with Azure AI Foundry models:
```
{
  "models": [
    {
      "title": "GPT-4o Azure",
      "provider": "azure",
      "model": "gpt-4o",
      "apiBase": "https://***.openai.azure.com",
      "deployment": "***",
      "apiKey": "***"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Codestral Azure",
    "provider": "mistral",
    "model": "codestral-latest",
    "apiBase": "https://***.models.ai.azure.com/v1",
    "apiKey": "***"
  }
}
```

Azure AI Foundry also offers the Cohere reranker, but I would not know how the config section should look like to use it...

**Comment by BastinFlorian** [comment]
@Patrick-Erichsen, @ulo's solution working like a charm for your information (autocomplete + chat).

**Comment by George-Const** [comment]
> > Although [@BastinFlorian](https://github.com/BastinFlorian) , to your original question regarding Codestral w/ Azure, we're still awaiting a reply as to whether or not this is possible. The Azure docs seem to imply that Codestral can only be used for Chat: https://learn.microsoft.com/en-us/azure/ai-studio/how-to/deploy-models-mistral-codestral?pivots=programming-language-python
> > If this is indeed the case we'll update the docs to make it clear that Codestral can't be used for Autocomplete with Azure.
> 
> In Azure AI Foundry, in my Codestral deployment details, I have 3 API routes including one route for FIM. When sending a post request to that route with a prompt and a suffix, it returns the code completion needed for Autocomplete. So using Codestral with Azure should be possible for Autocomplete. I don't know how API calls are made in Continue.dev for Azure AI Foundry models but I am not sure the `azure-ai-inference` package includes an easy way to do FIM for now.
> 
> ![Image](https://github.com/user-attachments/assets/6b1fd87e-a3c5-4c24-9223-eae8c3eea3bb)

For which region?
I recently deployed codestral to sweden central and cannot find the fim endpoint.

**Comment by nickthecook** [comment]
>  I recently deployed codestral to sweden central and cannot find the fim endpoint.

I just deployed to canadaeast via AI Foundry and see the same: just one endpoint, for `models/chat/completions`. No FIM. I can access the chat endpoint in curl, but when I try `v1/fim/completions` I get a 404.

Following [the docs](https://docs.continue.dev/customize/model-providers/azure#autocomplete-model), but my `apiBase` doesn't match that format. I have this:

`https://xxxxxxxx-resource.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview`

Does Continue support Codestral the way I've deployed it?

**Comment by George-Const** [comment]
> >  I recently deployed codestral to sweden central and cannot find the fim endpoint.
> 
> I just deployed to canadaeast via AI Foundry and see the same: just one endpoint, for `models/chat/completions`. No FIM. I can access the chat endpoint in curl, but when I try `v1/fim/completions` I get a 404.
> 
> Following [the docs](https://docs.continue.dev/customize/model-providers/azure#autocomplete-model), but my `apiBase` doesn't match that format. I have this:
> 
> `https://xxxxxxxx-resource.services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview`
> 
> Does Continue support Codestral the way I've deployed it?

I had the same. Deployed a second time to sweden, not sure why but the second deployment has the fim endpoint as well and all works fine. The only difference I see is that I specifically had to diselect the content filter when deploying model in azure foundry.

**Comment by nickthecook** [comment]
Interesting, I'll try deploying again.

Do you mean "all works fine" as in Continue will use the FIM successfully? Is that just following [these docs](https://docs.continue.dev/customize/model-providers/azure#autocomplete-model)?

**Comment by George-Const** [comment]
> Interesting, I'll try deploying again.
> 
> Do you mean "all works fine" as in Continue will use the FIM successfully? Is that just following [these docs](https://docs.continue.dev/customize/model-providers/azure#autocomplete-model)?

Yes works fine. Both for fim and chat.

**Comment by George-Const** [comment]
> > Interesting, I'll try deploying again.
> > 
> > Do you mean "all works fine" as in Continue will use the FIM successfully? Is that just following [these docs](https://docs.continue.dev/customize/model-providers/azure#autocomplete-model)?
> 
> Yes works fine. Both for fim and chat.

I double-checked. For model I used Codestral-2501 and not codestral-latest as indicated in the article you provided. Codestral-2501 is the actual model name in azure.

**Comment by bebeo92** [comment]
This config seem work to me, at least I can see request in metric tab on azure

```json
"tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "azure",
    "model": "Codestral-2501",
    "apiBase": "azure api base",
    "apiType": "azure-foundry",
    "apiKey": "key",
    "apiVersion": "2024-05-01-preview",
    "deployment": "deploymentName"
  },
```

**Comment by George-Const** [comment]
> This config seem work to me, at least I can see request in metric tab on azure
> 
> ```json
> "tabAutocompleteModel": {
>     "title": "Codestral",
>     "provider": "azure",
>     "model": "Codestral-2501",
>     "apiBase": "azure api base",
>     "apiType": "azure-foundry",
>     "apiKey": "key",
>     "apiVersion": "2024-05-01-preview",
>     "deployment": "deploymentName"
>   },
> ```

I think for FIM to work you still need to use mistral for provider and your apiBase should end with /v1 :)

**Comment by BastinFlorian** [comment]
**Azure does not offer autocomplete model for codestral, only chat completion codestral** 
To use codestral as an autocomplete, you need to deploy it in Mistral. 
It is very disappointing from Azure by the way

**Comment by Patrick-Erichsen** [comment]
@BastinFlorian - are these docs just flat-out wrong then? https://docs.continue.dev/customize/model-providers/azure#autocomplete-model

Wondering if they should be updated to just state that there is no autocomplete offering on Azure.

**Comment by njaku21** [comment]
> [@BastinFlorian](https://github.com/BastinFlorian) - are these docs just flat-out wrong then? https://docs.continue.dev/customize/model-providers/azure#autocomplete-model
> 
> Wondering if they should be updated to just state that there is no autocomplete offering on Azure.

Codestral autocomplete via Foundry has definitely worked for me up until (assumedly) a recent Continue.dev update. No change to API endpoints or keys on my end, just not working as of recent. I decided to rewrite my config in yaml to see if there is any difference in behavior but it appears not. 

I get "JSON.parse(...)?.error?.replace is not a function" with apiType: azure-foundry 

Sometimes I get "Unexpected token 'N', "NOT FOUND" is not valid JSON" instead

I will be digging into troubleshooting further but it hasn't been an annoying enough issue until today for me on my work assets. 

A possibly important thing to note is codestral currently works via chat but not for autocomplete. So the API is handshaking and presumably my config is correct(especially since it worked great before). I have also dabbled with Azure AI services and serverless deployments in Foundry and both seem to have issues. They each seem to have slightly different endpoint configurations but I am not sure of the downstream effect with continue.dev. 

Azure AI Services Hosted URL: https://[Project].services.ai.azure.com/models/chat/completions?api-version=2024-05-01-preview

Serverless URL: https://[deployment name].eastus.models.ai.azure.com(also exposes a /swagger.json)

Some kind of test-all-configured-model-methods button would be nice to have in the settings for more obvious outputs on this kind of troubleshooting. 

I at least can use chat with this config: 
```
- name: Codestral
    provider: azure # azure-foundry does not work here
    model: codestral-2501
    apiBase: https://[project].services.ai.azure.com
    apiKey: [key] # If you use subscription key, try using Azure gateway to rename it apiKey
    requestOptions:
      caBundlePath: [optional_cert]
    env:
      deployment: Codestral-2501
      apiType: azure # azure here works for chat but not code completion. azure-foundry does not work for either, gives the error noted above.
    roles:
      - autocomplete
      - chat
```

further testing with modified model settings(projectTemplates>autocomplete) gives(note the different api-version date) :
```
HTTP 404 Resource Not Found from https://[project].services.ai.azure.com/v1/completions?api-version=2023-07-01-preview {"error":{"code":"404","message": "Resource not found"}}
```

if I add autocomplete to gpt-4o-mini it does attempt to autocomplete so it seems to be isolated to the config with codestral. 

![Image](https://github.com/user-attachments/assets/6c2af7d7-f293-40c5-87bc-a9ffb54877db)

```
- name: GPT-4o-Mini
    provider: azure
    model: gpt-4o-mini
    apiBase: https://[project]openai.azure.com
    apiKey: [key] # If you use subscription key, try using Azure gateway to rename it apiKey
    env:
      deployment: gpt-4o-mini
      apiType: azure-openai # Or "azure-openai" if using OpenAI models
    requestOptions:
      caBundlePath: [optional_cert]
    roles:
      - autocomplete
      - chat
```

**Comment by Patrick-Erichsen** [comment]
@2mas can you try downgrading to an older version of Continue and see if that same config that was working previously is still working? That would help determine if its us or Azure

I think this is what your Codestral config should look like though

```yaml
- name: Codestral
    provider: azure 
    model: codestral-2501
    apiBase: https://[project].services.ai.azure.com
    apiKey: [key] # If you use subscription key, try using Azure gateway to rename it apiKey
    requestOptions:
      caBundlePath: [optional_cert]
    env:
      apiType: azure-foundry
    roles:
      - autocomplete
      - chat
```

Here's where we use those `env` configs to determine the endpoint: https://github.com/continuedev/continue/blob/main/core/llm/llms/OpenAI.ts#L199-L222

**Comment by George-Const** [comment]
@Patrick-Erichsen @BastinFlorian FIM works just fine but the azure foundry deployment must have the fim endpoint like so: 

![Image](https://github.com/user-attachments/assets/4f2ba8ca-113d-41df-bf77-860fdea7f4a5)

It used to not have it before, at least for sweden from what I've noticed, I just tried deploying another instance and as you can see the fim endpoint is there. 
Then I had to use mistral as provider instead of azure (otherwise it's not working indeed): 

```
  - name: Codestral azure new
    provider: mistral
    model: Codestral-2501
    apiBase: https://Codestral-2501-rkfug.swedencentral.models.ai.azure.com/v1
    apiKey: ******
    roles:
      - chat
      - edit
      - apply
      - autocomplete
```

With this config, fim and chat work fine.

**Comment by nickthecook** [comment]
Thanks for the config and the screenshot.

When I deployed Codestral in canadacentral and canadaeast a couple weeks ago I didn't get the FIM endpoint, just the chat endpoint.

I know Azure's feature support varies by region, especially with new stuff like AI, so I assume this is just a per-region thing. Hopefully they roll it out to more regions soon.

**Comment by njaku21** [comment]
> [@Patrick-Erichsen](https://github.com/Patrick-Erichsen) [@BastinFlorian](https://github.com/BastinFlorian) FIM works just fine but the azure foundry deployment must have the fim endpoint like so:
> 
> ![Image](https://github.com/user-attachments/assets/4f2ba8ca-113d-41df-bf77-860fdea7f4a5)
> 
> It used to not have it before, at least for sweden from what I've noticed, I just tried deploying another instance and as you can see the fim endpoint is there. Then I had to use mistral as provider instead of azure (otherwise it's not working indeed):
> 
> ```
>   - name: Codestral azure new
>     provider: mistral
>     model: Codestral-2501
>     apiBase: https://Codestral-2501-rkfug.swedencentral.models.ai.azure.com/v1
>     apiKey: ******
>     roles:
>       - chat
>       - edit
>       - apply
>       - autocomplete
> ```
> 
> With this config, fim and chat work fine.

Microsoft must have been having an outage with their serverless endpoints in some regions. I know that I definitely did not have these routes last week(I must have prior as it was working for me prior), but I do have them today in Foundry and FIM is properly working for me now. Something to note in the future since I looked and didn't see any obvious reports of issues with Codestral in Foundry. 

I guess I should have tried interacting with the API directly before assuming it was caused by a Continue update😅

my slightly-different config using the Serverless that also works fwiw

```
  - name: Codestral
    provider: mistral
    model: codestral-latest
    apiBase: https://[deployment-name].eastus.models.ai.azure.com/v1
    apiKey: [key] # If you use subscription key, try using Azure gateway to rename it apiKey
    requestOptions:
      caBundlePath: [optional cert]
    roles:
      - autocomplete
      - chat
```

using the Azure AI Services endpoint(both Serverless and Azure AI services endpoints are created automatically when deploying) does not work for autocomplete, only chat. 

```
  - name: Codestral 2
    provider: azure
    model: codestral-2501
    apiBase: https://[project].services.ai.azure.com/models
    api-version: 2024-05-01-preview
    apiKey: [key] # If you use subscription key, try using Azure gateway to rename it apiKey
    requestOptions:
      caBundlePath: [optional cert]
    env:
      deployment: codestral-2501
      apiType: azure
    roles:
      - autocomplete
      - chat
```

**Comment by GHuyHuynh** [comment]
Seem like alot of people have this issue. Any fixes or plans coming soon? Thank you

**Comment by Patrick-Erichsen** [comment]
@GHuyHuynh this thread is a bit all over the place, mind sharing what your particular issue/config is?

**Comment by GHuyHuynh** [comment]
Thank you for looking into this @Patrick-Erichsen . I was able to use Codestral autocomplete model through Azure Machine Learning Studio instead of AI Foundry. I created PR #6682  for document update, would you mind take a look. Thank you for your help.

**Comment by Patrick-Erichsen** [comment]
Thanks for the docs update! 🚀

**Comment by MESC2020** [comment]
@GHuyHuynh I'm planning to subscribe to the Azure Machine Learning service (vs studio) and will have to select an appropriate VM. Could you share what you chose and if it was sufficient?

**Comment by GHuyHuynh** [comment]
@MESC2020 Hi, I'm currently using Codestral-2501 with serverless endpoints so I don't know much about the VM options. Do you have a model in mind?

**Comment by MESC2020** [comment]
> [@MESC2020](https://github.com/MESC2020) Hi, I'm currently using Codestral-2501 with serverless endpoints so I don't know much about the VM options. Do you have a model in mind?

@GHuyHuynh I was actually not aware that Azure ML Studio offers serverless endpoints, I will check that out instead to use Codestral-2501 - thank you!

**Comment by MESC2020** [comment]
@GHuyHuynh  There seems to be an issue with the recommended Codestral config, introduced with PR [#6682](https://github.com/continuedev/continue/pull/6682).

When using the config: `provider: mistral`, continue will always append `/chat/completions` so `fim` endpoint can't be reached

I had to use `provider: openai` which only appends `/completions`, so it works with `fim`

```
- name: Codestral autocomplete
    provider: openai
    model: Codestral-2501
    apiBase: https://name.region.models.ai.azure.com/v2/fim/
    apiKey: <key>
    fim: true
    roles:
      - autocomplete
```

**Comment by GHuyHuynh** [comment]
Hi @MESC2020 , this is a good found. I was not aware of this when I use Codestral with Continue. My PR was just update the service from Azure AI Foundry to Azure Machine Learning Service. I also just saw your Issue #7304, I will see what I can help and let me know if you find something.

**Comment by MESC2020** [comment]
@GHuyHuynh  I appreciate. Yea the conversation is a little bit spread at this point. There's a similiar issue here: [7178](https://github.com/continuedev/continue/issues/7178)

All in all it seems like Mistral or continue is causing an issue with autocomplete.

**Comment by nodesiremonk** [comment]
Any update on this issue?

It seems the `provider: openai` trick suggested by @MESC2020 no longer works.

No error message in VS Code and the Azure metrics shows incoming requests, but input/output token count is 0

**Comment by ulo** [comment]
For me, both provider settings still work fine (`openai` and `mistral`, tested in Continue extension version 1.2.16).
I have a Microsoft Foundry with Codestral (and other models) deployed, which I use for chat and edit. And I also have a "serverless endpoint" in an Azure Machine Learning workspace, which I only use for autocomplete.
Here is the relevant config:
```
  - name: Codestral Foundry
    provider: azure
    model: Codestral-2501
    apiKey: ...
    apiBase: https://my-own-foundry.cognitiveservices.azure.com
    roles: [chat, edit, apply]
  - name: Codestral MLstudio mistral
    provider: mistral
    model: codestral
    apiKey: ...
    apiBase: https://codestral.swedencentral.models.ai.azure.com/v1
    roles: [autocomplete]
  - name: Codestral MLstudio openai v1
    provider: openai
    model: codestral
    apiKey: ...
    apiBase: https://codestral.swedencentral.models.ai.azure.com/v1/fim
    roles: [autocomplete]
  - name: Codestral MLstudio openai v2
    provider: openai
    model: codestral
    apiKey: ...
    apiBase: https://codestral.swedencentral.models.ai.azure.com/v2/fim
    roles: [autocomplete]
```
All 3 autocomplete models work fine. But the `apiBase` has to be different for `openai` and `mistral` providers (also the `mistral` provider will not work with the FIMv2 API).

**Comment by JulietteV** [comment]
Hi,

This is my config, with Continue 1.2.11:

```
name: MyConfig
version: 1.0.0
schema: v1

models:
  - name: Codestral-2501
    provider: azure
    model: Codestral-2501
    apiBase: https://myownservice.cognitiveservices.azure.com/
    apiKey: ***
    roles:
      - chat
      - edit
      - autocomplete
```

With this configuration, chat works, but editing and autocomplete do not. For these two functions, I get the following error message:
`Unexpected token 'N', "NOT FOUND" is not valid JSON`
