### ISSUE TITLE
YAML config: YAML anchoring not supported

### ISSUE THREAD

**Issue by SpeedCrash100** [continuedev/continue#4052]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Arch Linux
- Continue version: 0.9.261 (pre-release)
- IDE version: vscode 1.97.0
```

### Description

New YAML config format cannot parse config with anchors. Common use case is to set common API key for openai  models and use `<<: *common` syntax when adding new models. See reproduce section for more info.

### To reproduce

1. Create a YAML config `config.yaml` with the following content:
```yaml
name: Home
version: 0.0.1
openrouter_model: &openrouter_model
  provider: openai
  apiBase: https://openrouter.ai/api/v1
  apiKey: <KEY>
  roles:
    - chat
models:
  - <<: *openrouter_model
    name: Openrouter Gemini 2.0 Flash Free
    model: google/gemini-2.0-flash-exp:free

```

2. Open a Chat and see error in UI:

![Image](https://github.com/user-attachments/assets/02e47274-74aa-455b-b484-d684c70d8dee)

![Image](https://github.com/user-attachments/assets/2b915d39-eb15-4587-baff-dce4ac09fbdf)

3. If use config without anchoring it will load:

```yaml
name: Home
version: 0.0.1

models:
  - provider: openai
    apiBase: https://openrouter.ai/api/v1
    apiKey: <KEY>
    roles:
      - chat
    name: Openrouter Gemini 2.0 Flash Free
    model: google/gemini-2.0-flash-exp:free

```

### Log output

```Shell
No related log entries found
```

**Comment by bufferoverflow** [comment]
I figured out how to do this 🎉  
You just need to define the YAML version with the `%YAML 1.1` header, e.g.

```yaml
%YAML 1.1
---
name: My config
version: "1"

model_defaults: &model_defaults
  provider: openai
  apiKey: my-api-key
  apiBase: https://api.example.com/llm

models:
- name: mistral
  <<: *model_defaults
  model: mistral-7b-instruct
  roles:
    - chat
    - edit

- name: deepseek-r1-distill-qwen-7b
  <<: *model_defaults
  model: deepseek-r1-distill-qwen-7b
  roles:
    - chat
    - edit

- name: qwen2.5-coder-7b-instruct
  <<: *model_defaults
  model: qwen2.5-coder-7b-instruct
  roles:
    - chat
    - edit

- name: qwen2.5-coder-7b
  <<: *model_defaults
  model: qwen2.5-coder-7b
  useLegacyCompletionsEndpoint: false
  roles:
    - autocomplete
```
