### ISSUE TITLE
continue vscode openai-compatible

### ISSUE THREAD

**Issue by guyujun** [continuedev/continue#4278]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The API provider seems insufficient. Is it possible to add OpenAI-compatible custom methods?

**Comment by guyujun** [comment]
https://ark.cn-beijing.volces.com/api/v3/

volcengine is a faster/popular API provider in china

**Comment by forrestgao** [comment]
{
"title": "DeepSeek R1",
"model": "EP-*******",
"contextLength": 128000,
"apiKey": "*******",
"apiBase": "https://ark.cn-beijing.volces.com/api/v3",
"Provider": "OpenAI"
}   Work for me, I can successfully ask questions and receive intelligent responses, but I still encounter the following error message every time I open VSCode:HTTP 401 Unauthorized from https://api.openai.com/v1/completions { "error": { "message": "Incorrect API key provided……

**Comment by guyujun** [comment]
I achieve this by utilizing v1 instead of v3, and it’s crucial to enable the `useLegacyCompletionsEndpoint` option. i m not sure temperature work or not.

```
{
      "title": "deepseek-r1",
      "model": "ep-20250214031836-p2wfd",
      "contextLength": 128000,
      "apiKey": "",
      "apiBase": "https://ark.cn-beijing.volces.com/api/v1/",
      "provider": "openai",
      "options.temperature": 0.6,
      "useLegacyCompletionsEndpoint": false
    },
    {
      "title": "deepseek-v3",
      "model": "ep-20250214020016-7c8z9",
      "contextLength": 128000,
      "apiKey": "",
      "apiBase": "https://ark.cn-beijing.volces.com/api/v1/",
      "provider": "openai",
      "options.temperature": 0.6,
      "useLegacyCompletionsEndpoint": false
    }
```

hope it helps for you.

**Comment by cwzsquare** [comment]
the same bug here. it's easy to get chat mode working for `火山方舟大模型`; but as for tabAutocompleteModel, vscode debug console  logs the following error: 
```
[Extension Host] Error generating autocompletion:  Error: HTTP 404 Not Found from https://ark.cn-beijing.volces.com/api/v3/completions

This may mean that you forgot to add '/v1' to the end of your 'apiBase' in config.json.
```
part of my config: 
```
  "tabAutocompleteModel": {
    "title": "DeepSeek Code",
    "model": "deepseek-v3-241226",
    "apiKey": "",
    "provider": "openai",
    "contextLength": 128000,
    "apiBase": "https://ark.cn-beijing.volces.com/api/v3"
    // "options.temperature": 0.6,
    // "useLegacyCompletionsEndpoint": false
  },
```

**Comment by irowbin** [comment]
When `apiBase` is added and even the model supports agent, the agent selection gets disabled and says not supported, that's not actually true.

![Image](https://github.com/user-attachments/assets/6586e4a6-ad43-4094-8ae1-e8dabbae2c9e)

Is there any workaround or settings for this to override the default settings?

**Comment by droid192** [comment]
could you please support 'openai compatible' apis? by pasting base api and the key? cant find this option

**Comment by cwtuan** [comment]
Add a config:
<img width="242" height="198" alt="Image" src="https://github.com/user-attachments/assets/fad8a49b-9579-4b6c-b1c4-8b689600938e" />

Example of using openai-compatible API such as qwen3-coder-plus:
```
name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Qwen3
    apiBase: https://dashscope-intl.aliyuncs.com/compatible-mode/v1
    provider: openai
    model: qwen3-coder-plus
    apiKey: YOUR_KEY
    capabilities:
      - tool_use
      - image_input
    roles:
      - apply
      - chat
      - edit
```

**Comment by peterwwillis** [comment]
For those who found this via searching on the web: here's the docs https://docs.continue.dev/guides/ollama-guide#method-3-manual-configuration

**Comment by alicekellings** [comment]
For anyone landing here from search, the usual pattern with OpenAI-compatible gateways is to treat the gateway as the OpenAI provider and set the base URL explicitly.

```yaml
models:
  - name: Wappkit GPT-5.5
    provider: openai
    model: gpt-5.5
    apiBase: https://api.wappkit.com/v1
    apiKey: YOUR_KEY
    roles:
      - chat
      - edit
      - apply
```

The detail I would double-check is the `/v1` suffix. If the base URL is missing it, clients often end up calling the wrong path.

I wrote this pattern down with a few coding-agent examples here: https://github.com/alicekellings/cursor-cline-token-budget

Disclosure: I maintain Wappkit (https://api.wappkit.com), so Wappkit is the endpoint I can verify. The same idea should work with any gateway that follows the OpenAI chat/completions shape.
