### ISSUE TITLE
Multiple models with autocomplete role in config.yaml

### ISSUE THREAD

**Issue by masq6r** [continuedev/continue#4306]
### Issue Category

Undocumented feature or missing documentation

### Issue Description

How can I choose the autocomplete model when I define a few models that have autocomplete role, in `config.yaml`? For example:

```
models:

  - name: qwen-coder
    provider: openai
    model: qwen-coder-turbo
    apiKey: redacted
    apiBase: https://url
    defaultCompletionOptions:
      maxTokens: 500
    roles:
      - autocomplete

  - name: Codestral
    provider: mistral
    model: codestral-latest
    apiKey: redacted
    defaultCompletionOptions:
      maxTokens: 500
    roles:
      - autocomplete
```
