### ISSUE TITLE
YAML config: model capabilities missing

### ISSUE THREAD

**Issue by SpeedCrash100** [continuedev/continue#4434]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Currently, only [config.json](https://docs.continue.dev/reference#models) haves fields for overriding if model capable of handling images or tools. 
The `config.ts` does not apply to config.yaml. [config.yaml](https://docs.continue.dev/reference#models) itself does not have fields for setting capability so users cannot set it if switched to YAML format.

### Solution

Add a capabilities field from JSON. So YAML can use:

```yaml
models:
  - name: model
    model: some-vision-model
    provider: ollama
    capabilities:
      uploadImage: true
      tools: false
```
