### ISSUE TITLE
Tools disabled (grayed out) with Claude Sonnet 3.7

### ISSUE THREAD

**Issue by mbrunnen** [continuedev/continue#4555]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

- OS: NixOS
- Continue version: 1.0.3
- IDE version: VSCode 1.96.2
- Model: Claude Sonnet 3.7
- config:
```yaml
name: Claude
version: 1.0.2
schema: v1
models:
  - uses: anthropic/claude-3-7-sonnet
    with:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
context: []
```
https://hub.continue.dev/noel/claude

### Description

I cannot activate the "Use Tools" feature, it is grayed out. I need this feature to make continue.dev a cursor replacement. I am using Claude with the model add-on.

### To reproduce

1. Start a new session
3. Hover over the tools symbol

### Log output

```Shell
This model does not support tool use
```

**Comment by mbrunnen** [comment]
Related to #4549.

**Comment by sammyvoncheese** [comment]
Show the model files for those providers you're trying.     Tooling support is done via string comparison of the model file against a list of tool providers.

from toolsupport.ts:

  bedrock: (model) => {
    // For Bedrock, only support Claude Sonnet models with versions 3.5/3-5 and 3.7/3-7
    if (
      model.toLowerCase().includes("sonnet") &&
      ["claude-3-5", "claude-3.5", "claude-3-7", "claude-3.7"].some((part) =>
        model.toLowerCase().includes(part),
      )
    ) {
      return true;
    }
  }

**Comment by mbrunnen** [comment]
> Show the model files for those providers you're trying. Tooling support is done via string comparison of the model file against a list of tool providers.
> 

I just use the very basic from anthropic:

```yaml
name: Claude 3.7 Sonnet
version: 1.0.0
schema: v1

models:
  - name: Claude 3.7 Sonnet
    provider: anthropic
    model: claude-3-7-sonnet-latest
    apiKey: ${{ inputs.ANTHROPIC_API_KEY }}
    roles:
      - chat
      - edit
      - apply
```
