### ISSUE TITLE
tabAutocompleteModel not work

### ISSUE THREAD

**Issue by JackyWongX** [continuedev/continue#4611]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:win11
- Continue version:1.0.3
- IDE version:1.98.1
- Model:ollama
- config:
  
  "tabAutocompleteModel": {
    "model": "qwen2.5-coder:1.5b",
    "title": "qwen2.5-coder:1.5b",
    "provider": "ollama",
    "apiBase": "http://127.0.0.1:11434"
  }
  
  OR link to assistant in Continue hub:
```

### Description

The chat mode works properly, but the completion does not respond at all, and there is no log. The ollama model is working properly locally, but there is no cpu and gpu load. Where is the log to check whether there is a call model and error message?

### Log output

```Shell

```

**Comment by owtaylor** [comment]
Is tab autocompletion enabled? There should be a checkmark next to the word "Continue" in the bottom bar.

If that's OK, then check "Continue - LLM Prompt/Completion" in the output view in the bottom panel - you should see completion requests to the model appearing there.

**Comment by JackyWongX** [comment]
autocompletion is enabled, and I also checked that the configuration in setting.json is enabled
continue in the status bar is also enabled

Continue - LLM Prompt/Completion Nothing is output

**Comment by owtaylor** [comment]
Can you attach the entire `config.json` here?

**Note:** This might be better handled in the help channel in Discord - configuring a tabAutocomplete model to point to an ollama hosted model *does* work in general, so something specific is going wrong with your setup; it's just hard to say what.

**Comment by jeepshop** [comment]
Since you didn't provide a complete JSON file it is hard to trouble shoot. But ALAS you should be using the new YAML syntax anyways.

Notes:
- You will want to tune _contextLength_ and _maxTokens_ for your server, as they greatly determine how much GPU memory Ollama will need (The numbers I used below will need ~40GB GPU)
- Pick the roles that you want you model to support, if you ONLY want to use it for autocomplete then remove the other ones.
- Also note AFAIK the _defaultCompletionOptions_ do NOT apply to autocomplete, and those use much smaller context windows. So you will get some lag as Ollama flips models on you if you jump between chat and auto-completion.

```YAML
name: Local Assistant
version: 0.0.1
models:
  - name: qwen2.5-coder:1.5b
    provider: ollama
    model: qwen2.5-coder:1.5b
    apiBase: http://YOUR_SERVER:11434
    roles:
      - summarize
      - chat
      - autocomplete
      - edit
      - apply
    defaultCompletionOptions:
      stream: true
      temperature: 0.7
      contextLength: 32768
      maxTokens: 16384
      keepAlive: 5

```
