### ISSUE TITLE
Publish YAML schema

### ISSUE THREAD

**Issue by electriquo** [continuedev/continue#4612]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The newer and preferred configuration format is YAML over JSON and it is not backward compatible, thus the [JSON schema](https://github.com/continuedev/continue/blob/main/extensions/vscode/config_schema.json) cannot be use with the YAML.

What do you think of publishing the YAML schema for many clear reasons.

### Solution

Publish a YAML schema for the configuration file.

**Comment by tomasz-stefaniak** [comment]
This isn't exactly what you're looking for but it might be helpful: 

https://github.com/continuedev/continue/blob/main/packages/config-yaml/src/schemas/index.ts

**Comment by rennokki** [comment]
I created a project by using the Continue's YAML schema's Zod declarations package that automatically compiles to JSON schema: https://github.com/theaifatherco/continue-dev-schema

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/theaifatherco/continue-dev-schema/refs/heads/main/schema.json

name: local-config
version: 0.0.1
schema: v1

# ...
```

```json
{
    "$schema": "https://raw.githubusercontent.com/theaifatherco/continue-dev-schema/refs/heads/main/schema.json",
    ...
}
```
