### ISSUE TITLE
YAML format is missing the keepAlive property

### ISSUE THREAD

**Issue by Impact123** [continuedev/continue#4671]
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

I wanted to migrate my configuration file to the YAML format but it seems to be missing the Ollama `keepAlive` property documented [here](https://docs.continue.dev/json-reference#completionoptions) and [here](https://docs.continue.dev/reference#completionoptions).
```yaml
models:
    - name: "..."
      provider: "ollama"
      ...
      defaultCompletionOptions:
          keepAlive: 300 # <-----
```
I tried adding it as shown above but it's not applied and does not show up in `Output > Continue - LLM prompt/Completion` either. Changing other options like `contextLength`  in the same place there works fine.

### Solution

Please support the `keepAlive` completion option in the YAML format too.

**Comment by j0-Da** [comment]
+1 to this.
Ollama is configured to keep the models loaded (keepalive=-1) and if i call ollama directly via terminal or with open-webui the models are loaded forever. 

Once my users use continue.dev without keepalive set or with it set they are always loaded for 30 mins (default for continue). And even overwrite my other keepalive settings. (Model previously loaded forever will be unloaded 30 mins later.)

**Comment by j0-Da** [comment]
Thanks! This is working as expected. Sorry for the inconvenience.

**Comment by TheNha** [comment]
+1

**Comment by thinkover33** [comment]
+1

**Comment by ZobairQ** [comment]
> It needs to go inside `completionOptions` and it will work. See links. This is strictly about the YAML format not supporting it.

can you please show an example, I can't get it to work

**Comment by TheTechromancer** [comment]
+1. Neither `completionOptions` nor putting the setting into individual models seems to work in the YAML config.

**Comment by aaronpliu** [comment]
how to forbid /api to update ollama's property setting?

**Comment by boecks** [comment]
I ran into the same issue around **model lifetime management**, but with the opposite goal: **unloading models as quickly as possible** instead of keeping them resident in memory.

While investigating, I found that this *is already supported*, but the solution is somewhat under-documented.

---

## Background

According to the Ollama FAQ:  
https://docs.ollama.com/faq#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

The Ollama API supports a `keep_alive` request parameter:

- `-1` → keep the model loaded indefinitely  
- `0` → unload immediately after the response finishes  
- `N` → keep the model loaded for `N` seconds  
- **Duration strings** (e.g. `5m`, `30s`) also work in practice

At the same time, the Continue docs mention:
https://docs.continue.dev/reference#models

```yaml
requestOptions:
  extraBodyProperties: Additional properties to merge with the HTTP request body
```

This allows passing `keep_alive` directly to Ollama, even though it isn’t explicitly documented as an example.

---

## Usage examples

### Keep the model loaded forever

```yaml
requestOptions:
  extraBodyProperties:
    keep_alive: -1
```

Result:

```
PS C:\Users\username> ollama ps
NAME                ID              SIZE      PROCESSOR    CONTEXT    UNTIL
qwen2.5-coder:7b    dae161e27b0e    8.2 GB    100% GPU     8192       Forever
```

---

### Unload the model immediately after the response

```yaml
requestOptions:
  extraBodyProperties:
    keep_alive: 0
```

Result (right after the response completes):

```
PS C:\Users\username> ollama ps
NAME                ID              SIZE      PROCESSOR    CONTEXT    UNTIL
qwen2.5-coder:7b    dae161e27b0e    8.2 GB    100% GPU     8192       Stopping...
```

---

### Keep the model loaded for 5 minutes

```yaml
requestOptions:
  extraBodyProperties:
    keep_alive: 5m  # alternatively: 600 (seconds)
```

Result:

```
PS C:\Users\username> ollama ps
NAME                ID              SIZE      PROCESSOR    CONTEXT    UNTIL
qwen2.5-coder:7b    dae161e27b0e    8.2 GB    100% GPU     8192       4 minutes from now
```

---

## Full example: Continue model config with `keep_alive`

```yaml
- name: SmallCoder
  provider: ollama
  apiBase: http://localhost:11434
  model: qwen2.5-coder:7b
  roles:
    - chat
    - edit
    - summarize
    - autocomplete
    - apply
  capabilities:
    - tool_use
  autocompleteOptions:
    debounceDelay: 150
    maxPromptTokens: 1024
  requestOptions:
    extraBodyProperties:
      keep_alive: 10m
```

---

## Suggestion

It might be helpful to **explicitly document `keep_alive` as a supported `extraBodyProperties` option** in the Continue docs, as it enables important control over memory/GPU usage—especially for users who want models to unload immediately.

See also: https://discord.com/channels/1108621136150929458/1417565615777910935/1448587579736981515
