### ISSUE TITLE
many models supports function call, shouldn't be too strict

### ISSUE THREAD

**Issue by leonzy** [continuedev/continue#4806]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config:
  

  
  OR link to assistant in Continue hub:
```

### Description

Deepseek V3 also support Function calls, thus it should enable tool use or agent mode

Actually If I use a custom model, it may support function calls, so we should not be too strict by only allow a few models enable tool use.

I suggest return true for all models, and let user choose use it or not

### Log output

```Shell

```

**Comment by sestinj** [comment]
@leonzy this is possible by adding the `tool_use` capability like this:

```yaml
models:
  - name: OpenAI GPT-4.1
    provider: openai
    model: gpt-4.1-2025-04-14
    apiKey: ${{ inputs.OPENAI_API_KEY }}
    capabilities:
      - tool_use
```
