### ISSUE TITLE
VS Code 1.0.5 Update Completely Ignores My JSON Settings

### ISSUE THREAD

**Issue by dabockster** [continuedev/continue#4862]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue version: 1.0.5
- IDE version: 1.98.2
- Model: All models
```

### Description

My Continue extension updated from 1.0.4 to 1.0.5, showing me the new features. They look awesome - if they worked. As soon as I tried to transmit a prompt to OpenRouter (via my JSON config), it errored out with something about a "free trial" being exceeded, even though I don't have the Continue free trial configured. I know that Continue is attempting to migrate to YAML, but I never saw any notice of needing to port my config over in the extension itself. The "open config file" option was also missing on the Settings screen.

### To reproduce

Update Continue in VS Code from 1.0.4 to 1.0.5.

### Log output

```Shell

```

**Comment by sestinj** [comment]
@dabockster this sounds very not good—mind sharing the contents (redacted however makes sense) of your ~/.continue/config.yaml and ~/.continue/config.json? Hoping this will let me pin down the problem ASAP so we can make sure this doesn't affect a bunch of others.

Our intention was: a) if you have a config.json already, we don't change anything at all, b) if you are a brand new user without config.json, then we make a config.yaml by default. Only later do we want to more actively help people migrate, hence "very not good"

On another note: you're right we should make the settings button more obvious, I think that was an oversight. Right now it's able to be accessed here in the assistants dropdown:

<img width="517" alt="Image" src="https://github.com/user-attachments/assets/9a64b6c5-3ac7-4ba8-b770-ed65456510bc" />

**Comment by armedi** [comment]
I also got same issue after upgrading from 1.0.4 to 1.0.5. It failed to pick up my custom prompt, it only sends the custom prompt name instead of the prompt content (I check the log of sent prompts into my OpenAI proxy).

This wrong behavior was temporarily fixed after I uninstall and install the extension again. But after several times of use, the same issue happened again. I uninstall and install multiple times already to get the custom prompt working

This is my config.yaml

```yaml
name: Local
version: 1.0.0
schema: v1
models:
  - name: GPT-4o
    provider: openai
    model: gpt-4o
    apiKey: sk-proj-0
    apiBase: "http://localhost:1212"
    useLegacyCompletionsEndpoint: false
    roles:
      - chat
      - edit
      - apply

  - name: GPT-4o Mini
    provider: openai
    model: gpt-4o-mini
    apiKey: sk-proj-0
    apiBase: "http://localhost:1212"
    useLegacyCompletionsEndpoint: false
    roles:
      - chat
      - edit
      - apply

context:
  - provider: file
  - provider: code
  - provider: diff
  - provider: currentFile
  - provider: terminal
  - provider: docs
  - provider: open
  - provider: web
  - provider: codebase
  - provider: folder
  - provider: search
  - provider: url
  - provider: clipboard
  - provider: tree
  - provider: problems
  - provider: debugger
  - provider: repo-map
  - provider: os

prompts:
  - name: refine
    description: Refine document
    prompt: |
      Read the provided documents or sections of documents. Respond with "I've processed the content of <names of all given documents>. Please let me know if there's anything specific you would like to change within this document(s)!". No other text is allowed in the first response.
      
      Following your initial response, the user may modify the document themselves and include the changes in their reply. Additionally, the user might insert a comment block within the changes to clarify their intended modifications. Ensure you understand these changes and only refine those specific parts, unless the user explicitly requests otherwise. This process will involve continuous, iterative interactions with the user, refining the document until the user is content.

      ## OUTPUT

      - Only output the specific part requested by the user, not the whole document.
      - Format output as a copyable markdown block. Do NOT write the file name at the top.
      - For numbering, use number `1` for all list items (not 1, 2, 3, etc) to simplify markdown authoring.

```
