### ISSUE TITLE
Error in Parsing config.yaml with clientCertificate added

### ISSUE THREAD

**Issue by AbhilashPal** [continuedev/continue#4916]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Ubuntu 24.04.1 LTS
- Continue version: 1.0.5
- IDE version: VS Code 1.98.2
- Model:Qwen/Qwen2.5-Coder-32B-Instruct-AWQ
- config:
  
models:
  - name: Qwen
    provider: openai
    model: Qwen/Qwen2.5-Coder-32B-Instruct-AWQ
    apiBase: https://[url]/api/v1
    apiKey: EMPTY
    requestOptions:
      clientCertificate:
        cert: C:/certs/ca-certificates.crt

    roles:
      - autocomplete
      - chat
  
  OR link to assistant in Continue hub:
```

### To reproduce

1. Use a vllm endpoint running on a VM or Pod which can be accessed as `https://[url]/api/v1`

### Log output

```Shell

```

**Comment by Patrick-Erichsen** [comment]
Hm, this should be handled here: https://github.com/continuedev/continue/blob/8d9341a0f00b2ebf6ac1d5192d5b6cd1227b63bf/packages/fetch/src/fetch.ts#L58

Are there any other [logs](https://docs.continue.dev/troubleshooting#check-the-logs) you can share?

**Comment by AbhilashPal** [comment]
I get the following : 

```
[Extension Host] Failed to parse rolled assistant: name: continue-xxx
version: 0.0.1
schema: v1

models:
  - name: xxx
      provider: openai
      model: /models/Nvidia-Llama-3.1-Nemotron-70B-Instruct-HF-AWQ-INT4/
      apiBase: https://xxx/api/v1/
      apiKey: EMPTY
      template: none
      defaultCompletionOptions: {}
      roles:
        - chat
  
  - name: xxx
    provider: openai
    model: Qwen/Qwen2.5-Coder-32B-Instruct-AWQ
    apiBase: https://xxx/api/v1
    apiKey: EMPTY
    requestOptions:
      clientCertificate:
        cert: C:/certs/ca-certificates.crt

    roles:
      - autocomplete
      - chat

prompts:
  - name: test
    description: Write unit tests for highlighted code
    prompt: |
      Write a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase

```
