### ISSUE TITLE
Support for AWS Bedrock-hosted Claude 3.7 Sonnet model with the new Agent API

### ISSUE THREAD

**Issue by uninstallit** [continuedev/continue#4923]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

The new Agent API currently supports Anthropic's Claude 3.7 Sonnet model when directly accessed. However, when attempting to use Claude 3.7 Sonnet via AWS Bedrock, the extension does not recognize the model and reports it as unsupported.

I expect the extension to allow me to use a supported model via AWS Bedrock. 

Could you please add support for recognizing and using Anthropic Claude models hosted on AWS Bedrock within the new Agent API?

**Comment by chezsmithy** [comment]
Could you share a bit more about what you are doing? Are you attempting to call AWS agents directly as a provider?

**Comment by uninstallit** [comment]
@chezsmithy I was just trying to turn on Agent mode with a Bedrock hosted Claude 3.7 Sonnet.

**Comment by chezsmithy** [comment]
@uninstallit yep. That would do it. Where did you overload the base model name in AWS? Just curious.

**Comment by uninstallit** [comment]
@chezsmithy Not sure - I didn't do the deployment - but I know we use another service in the middle so the model name change might not be in Bedrock.

**Comment by chezsmithy** [comment]
@uninstallit got it. Recommend changing the name if possible to match the patterns in tools support.

**Comment by larsr** [comment]
I'm actually using claude-3.7-sonnet on AWS right now.

I have this in my config.json

    {
      "title": "Claude 3.7 Sonnet on AWS",
      "provider": "bedrock",
      "model": "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
      "region": "us-east-1",
      "profile": "my-aws-profile"
    }

I haven't gotten it to work with the new config.yaml format yet, because there is some bug with how continue gets the aws credentials (which is what i came here to report...)

**Comment by kintz09** [comment]
I'm dealing with the same issue right now. Finally got all the various models I needed added to Open WebUI and my Claude 3.7 Sonnet model isn't supporting agent mode. Our Claude models also come from Bedrock but we hit our private API from Open WebUI. The model's default name is `us.anthropic.claude-3-7-sonnet-20250219-v1:0` for us.

**Comment by kintz09** [comment]
For anyone else that may run into this issue, I just found the manual fix thanks to the [exmaple config for Claude 4 Sonnet in the Hub](https://hub.continue.dev/anthropic/claude-4-sonnet?view=config).

```yaml
name: Claude 4 Sonnet
version: 1.0.2
schema: v1

models:
  - name: Claude 4 Sonnet
    provider: anthropic
    model: claude-sonnet-4-20250514
    apiKey: ${{ inputs.ANTHROPIC_API_KEY }}
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 200000
      maxTokens: 64000
    capabilities:
      - tool_use
      - image_input
```

As soon as I added `tool_use` to my model config it immediately unlocked agent mode.
