### ISSUE TITLE
Chat not working with local models

### ISSUE THREAD

**Issue by evgenyigumnov** [continuedev/continue#5136]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue version: 1.0.8
- IDE version: Idea IntelliJ IDEA 2024.3.5 (Ultimate Edition)
- Model:any model
- config:
  
name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: qwen2.5-coder-14b-instruct
    provider: lmstudio
    model: qwen2.5-coder-14b-instruct
    apiBase: http://localhost:1234/v1
  - name: qwen2.5-coder-14b-instruct
    provider: lmstudio
    model: qwen2.5-coder-14b-instruct
    apiBase: http://localhost:1234/v1
    roles:
      - autocomplete
  - name: text-embedding-nomic-embed-text-v1.5@q4_0
    provider: lmstudio
    model: text-embedding-nomic-embed-text-v1.5@q4_0
    apiBase: http://localhost:1234/v1
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase

  
  OR link to assistant in Continue hub:
```

### Description

Autocomplete working but Chat not working!

![Image](https://github.com/user-attachments/assets/7faeb420-a6c2-4354-9fd4-54f3db16f63b)

### Log output

```Shell

```

**Comment by yufangbo** [comment]
@evgenyigumnov Could you please share the configuration of vllm deployment? Why did I deploy the qwen2.4-coder-32b-instruct model for the code completion function, but the effect was very poor?

**Comment by mohamed-benali** [comment]
Getting the exact same error message when trying to connect with lmstudio, also windows 11 (pycharm)

**Comment by tomasz-stefaniak** [comment]
Could you try this solution and see if it works for you?

https://discord.com/channels/1108621136150929458/1157400632534245386/1373054963928006757

```
name: Local Assistant
version: 1.0.0
schema: v1

models:
  - name: Qwen2.5-Coder-7B-Instruct
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: StableCode-Instruct-3B
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: Qwen2.5-Coder-3B-Instruct
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: DeepSeek-V3-0324-Pruned-Coder-411B
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: DeepSeek-Coder-V2-Lite-Instruct
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: Gemma3-12B-Claude-3.7-Sonnet
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: Qwen2.5-Coder-32B-Instruct
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: DeepSeek-Coder-6.7B-Instruct
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: Qwen2.5-Coder-3B-Instruct-Dup
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: Qwen2.5-Coder-1.5B-Instruct
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: StarCoder2-7B
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: DeepSeek-Coder-6.7B-Instruct-Dup
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_S
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: Qwen2.5-Coder-14B-Instruct
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

  - name: Autodetect
    provider: openai
    model: gpt-4
    apiBase: http://localhost:1234/v1/

defaultModel: Qwen2.5-Coder-7B-Instruct

contextProviders:
  - name: code
  - name: docs
  - name: diff
  - name: terminal
  - name: problems
  - name: folder
  - name: codebase

experimental:
  agentMode: true
  allowAnyModelInAgentMode: true
  promptPath: custom/.prompts
  useChromiumForDocsCrawling: true
  autoAcceptChanges: true
  autoRunTerminalCommands: true

completionOptions:
  temperature: 0.7
  maxTokens: 2048

systemMessage: You are an AI assistant capable of using tools and performing actions autonomously in agent mode.

allowAnonymousTelemetry: false
```

I think there's a chance it has something to do with a missing trailing slash in `apiBase` (just a hunch).
