### ISSUE TITLE
[OpenAI Compatible API] The context input is reduced when using openai provider

### ISSUE THREAD

**Issue by TheNha** [continuedev/continue#5208]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux
- Continue version: 1.0.5
- IDE version: March 2025 (version 1.99)
- Model: Qwen2.5 Coder with ctx-size 32000
- config:
  
  models:
  - name: "Qwen2.5"
    provider: "openai"
    model: "Qwen2.5"
    apiBase: "http://localhost:xxx/v1"
    defaultCompletionOptions:
      contextLength: 32000
      maxTokens: 4096
```

### Description

When I use the configuration as ollama, I check the logs in the ollama server and see the full content the user sent in, and the correct answer. It about 9k token.

This is my ollama configuration.
  ```yaml
  models:
  - name: "Qwen2.5"
    provider: "ollama"
    model: "Qwen2.5"
    apiBase: "http://localhost:xxx"
    defaultCompletionOptions:
      contextLength: 32000
      maxTokens: 4096
  ```

But when I use the provider as openai, the same content and user question, I check and see that the server logs are missing data at the beginning, so the answer is missing and incomplete. It only has ~2k tokens left.

Because I use another framework to create flows and expose via openai compatible api so i have to configure provider as openai compatible API.
 Why the context input is reduced when using openai provider? How to config or fix this problem. Thanks you.

### Log output

```Shell

```
