### ISSUE TITLE
Unexpected non-whitespace character after JSON

### ISSUE THREAD

**Issue by drakgoku** [continuedev/continue#5253]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue version: latest
- IDE version: latest
- Model: any model.
- config:
  : Gemini 2.5 Pro Beta
version: 1.0.1
schema: v1

models:
  - name: Gemini 2.5 Pro
    provider: gemini
    model: gemini-2.5-pro-exp-03-25
    apiKey: ${{ inputs.GEMINI_API_KEY }}
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 1048576
      maxTokens: 65536

  
  OR link to assistant in Continue hub:
```

### Description

The image is explained without words.

![Image](https://github.com/user-attachments/assets/379f7009-8882-4cc7-a6b6-9df8483ba1a5)

### To reproduce

The agent doesn't work. It can be reproduced with anything.

### Log output

```Shell

```

**Comment by drakgoku** [comment]
https://github.com/continuedev/continue/issues/5209
https://github.com/continuedev/continue/issues/2024

I see this isn't an isolated problem. I understand I'm going to Roo Code Augur.

**Comment by drakgoku** [comment]
It's a continue problem. Bye.
![Image](https://github.com/user-attachments/assets/22d764e6-fa27-4c79-a63a-9ed97b9939ec)

**Comment by drakgoku** [comment]
It's a continue problem. Bye.
![Image](https://github.com/user-attachments/assets/2a5b0f50-55e5-41ea-9787-2f99497a6423)

**Comment by dgenezini** [comment]
Same for me. Looks like continue is trying to read the old(?) json format for the config file.

**Comment by uinstinct** [comment]
can you please share the link of the hub config that you are using and the continue extension version?

**Comment by dgenezini** [comment]
> continue

Do you mean the config file? If so:

<details><summary>Details</summary>
<p>

```yaml
name: Local Assistant
version: 1.0.0
schema: v1

models:
  - name: codellama
    provider: ollama
    model: ollama:latest
    apiBase: http://localhost:11434/llama2
    roles:
      - chat
      - edit
      - apply
  - name: Llama3.1 Chat
    provider: ollama
    model: llama3.1:8b
    apiBase: http://localhost:11434/llama2
    roles:
      - chat
  - name: qwen2.5-coder:1.5b-base
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    apiBase: http://localhost:11434/llama2
    roles:
      - autocomplete
  - name: nomic-embed-text:latest
    provider: ollama
    model: nomic-embed-text:latest
    apiBase: http://localhost:11434/llama2
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase

``` 

</p>
</details>
