### ISSUE TITLE
Cannot use remote ollama server due to incorrect URL.

### ISSUE THREAD

**Issue by jesseVast** [continuedev/continue#5274]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: OSX
- Continue version: 1.0.6
- IDE version: 1.99.3
- Model: llama3.1:8b
- config:
  
  name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Llama 3.1 8B
    provider: ollama
    model: llama3.1:8b
    roles:
      - chat
      - edit
      - apply
  - name: Qwen2.5-Coder 1.5B
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    roles:
      - autocomplete
  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed
  - name: Llama3.2 3B
    provider: ollama
    model: llama3.2:3b
    roles:
      - chat
  - name: Llama3.1 8B Remote
    provider: ollama
    model: llama3.1:8b
    roles:
      - chat
    apiBase: http://gpu1:11434/v1/
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase% 
  
  OR link to assistant in Continue hub:
```

### Description

The API end point is looking for <URL>/v1/api which does not exist.  See attached image for the URL it is looking for.

![Image](https://github.com/user-attachments/assets/7386c2e4-5399-4319-8a24-2f61cc7790db)

Results from the openai api call to the remote server. 

```
curl http://gpu1:11434/v1/chat/completions \  
    -H "Content-Type: application/json" \
    -d '{
        "model": "llama3.1:8b",     
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "Hello!"
            }
        ]
    }'
{"id":"chatcmpl-809","object":"chat.completion","created":1745267595,"model":"llama3.1:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":"How can I assist you today? Do you have any questions or need help with something specific, or would you like to just chat for a bit?"},"finish_reason":"stop"}],"usage":{"prompt_tokens":23,"completion_tokens":31,"total_tokens":54}}
```

### To reproduce

1) Edit ~/.continue/config.yaml and point to a model on a remote ollama server. 
2) Try chat with the model. 

### Log output

```Shell

```

**Comment by PlebeiusGaragicus** [comment]
I have been using a remove Ollama server without issue.

Specifically, I'm using a self-hosted Open WebUI.  It exposes its Ollama API if you add `/ollama`

So, `https://mywebsuite.com/ollama` - it needs an API key which Open WebUI provides.

It's been working, but I've been having trouble with Agent mode - probably a problem with the LLMs I'm using.  Chat works fine.

**Comment by Patrick-Erichsen** [comment]
@PlebeiusGaragicus mind sharing your relevant config?

**Comment by neikist** [comment]
```yaml
...
home_ollama_server: &home_ollama_server
  provider: ollama
  apiBase: http://192.168.0.42:11434

models:
  - name: qwen2.5-coder 7b on home server
    <<: *home_ollama_server
    model: qwen2.5-coder:7b-instruct
    roles:
      - autocomplete
      - edit
      - chat
      - apply
      - summarize
 ...
```
With this config and continue 1.015 for jetbrains products I get this error:
Failed to load model:
Name: qwen2.5-coder 7b on home server
Model: qwen2.5-coder:7b-instruct
Provider: ollama
Invalid URL

At the same time it works for http://localhost:11434

**Comment by Patrick-Erichsen** [comment]
Hmm, there shouldn't be any issue with the yaml anchors but just as a sanity check could you try this?

```yaml  
models:
  - name: qwen2.5-coder 7b on home server
    provider: ollama
    apiBase: http://192.168.0.42:11434
    model: qwen2.5-coder:7b-instruct
    roles:
      - autocomplete
      - edit
      - chat
      - apply
      - summarize
```
