### ISSUE TITLE
file context provider throw error on smaill file

### ISSUE THREAD

**Issue by AndrewTsao** [continuedev/continue#5291]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version: 1.0.6
- IDE version: 1.96.2
- Model:
- config:
  

  
  OR link to assistant in Continue hub:
```

### Description

When I use @file in Continue to reference a file, if the code exceeds 12K or 400 lines, it directly gives me the following error: "'demo.py' is 170.1 KB which exceeds the allowed context length and cannot be processed by the model." This is clearly incorrect, as my model can handle a context of 128K tokens.

### Log output

```Shell

```

**Comment by AndrewTsao** [comment]
![Image](https://github.com/user-attachments/assets/6df41552-dc94-4d69-8fe3-675b1a29f9c0)

**Comment by GrimmiMeloni** [comment]
Seeing this with VScode on recent 1.0.6 release version as well.
Maybe due to changes to context size defaults in v1.0.6?

I was able to get it working again, by tweaking my local setup and adding contextLength option in the config yaml like this:

```yaml
models:
  - name: Gemma 3 27B
    provider: ollama
    model: gemma3:27b
    defaultCompletionOptions:
     contextLength: 131072
    roles:
      - chat
      - edit
      - apply

```

**Comment by GrimmiMeloni** [comment]
Probably related changes: #4602 and #4929 - maybe @Jazzcort and/or @RomneyDa can chime in?

**Comment by Jazzcort** [comment]
@AndrewTsao Can you just check if `contextLength` is correctly set to 128k in your config.yaml like what @GrimmiMeloni did? For code context, 400 lines might be around 4000 tokens so if your `contextLength` is set to 128k this warning won't pop up.

**Comment by GrimmiMeloni** [comment]
Just for clarification - for me at least the unchanged setup (without the `defaultCompletionOptions`) worked till last week.
Then after a break over the weekend, I now today found continue to give the aforementioned error regarding context length.

So maybe this is more like an expected breaking change, in the sense that from 1.0.6 forward, the config.yaml must include these settings?

**Comment by Jazzcort** [comment]
@GrimmiMeloni Forbidding file mention for files that have token size larger than context length is a new feature in 1.0.6. You can see the announcement in the 1.0.6 release. If you don't set `contextLength` in config.yaml, Continue will first ask your backend provider for this value and if context length is also not set there, context length will be set to 8192 as a default value.

**Comment by GrimmiMeloni** [comment]
Understood.
That would mean in my case that ollama is not providing the context length via its API, although it knows the model's meta data.

```shell
$ ollama show gemma3:27b
  Model
    architecture        gemma3
    parameters          27.4B
    context length      131072
    embedding length    5376
    quantization        Q4_K_M
```

Is there any way to drill deeper, e.g. see the request the continue makes to ollama to introspect the model?

**Comment by GrimmiMeloni** [comment]
I tried that, but I don't see continue sending any context size information when removing the entry in the configuration.

<img width="882" alt="Image" src="https://github.com/user-attachments/assets/b5d1950d-4959-4fc7-92c9-9aa5022df847" />

Based on the output from `ollama serve` it seems that ctxSize is getting defaulted to 8k instead of the supported size according to the model meta information. 

```
time=2025-04-23T23:22:28.926+02:00 level=INFO source=server.go:405 msg="starting llama server" cmd="/Applications/Ollama.app/Contents/Resources/ollama runner --ollama-engine --model /Users/mhess/.ollama/models/blobs/sha256-e796792eba26c4d3b04b0ac5adb01a453dd9ec2dfd83b6c59cbf6fe5f30b0f68 --ctx-size 8192 --batch-size 512 --n-gpu-layers 63 --threads 8 --parallel 1 --port 59864"
```

**Comment by AndrewTsao** [comment]
This is my config.yaml:
```yaml
name: Local Assistant
version: 1.0.0
schema: v1

models:
  - model: Qwen2.5-Coder-32B-Instruct
    name: Qwen2.5-Coder-32B-Instruct
    provider: openai
    apiKey: sxxxx
    apiBase: http://hpc-xxxx:2002/v1
    systemMessage: 你是一个专业的软件开发助手，请用中文尽量清洁明了地回答问题。
    defaultCompletionOptions:
      temperature: 0.6

    roles:
      - chat
      - edit
      - apply
      - autocomplete
    ```

![Image](https://github.com/user-attachments/assets/812203bb-a30f-407b-a29f-bec80900581a)

then, throw the error message box.

![Image](https://github.com/user-attachments/assets/f72f55a0-1cdc-4fcf-a72f-29fe71c63cf5)
