### ISSUE TITLE
Prompt blocks are not including codeblocks

### ISSUE THREAD

**Issue by nomagicln** [continuedev/continue#5363]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux, but possibly operating system agnostic 
- Continue version: 1.1.26
- IDE version: VSCode 1.99.3
- Model: QwQ:32b
- config:
  

  
  OR link to assistant in Continue hub:

- prompts:
  
Name: Write Function Comment
description: Generate function comment according the function content
version: 1
---
<system>
  You are expert in coding and architecture
</system>

<responsibility>
  Write comments according to the specified format
</responsibility>

<format>
    <function-comment-format>
    // Function name: Summary of function purpose
    //
    // Business purpose:
    //  1. Business purpose 1
    //  2. Business purpose 2
    //  ...
    //
    // Parameters:
    //   - Input 1: Description of input 1
    //   - Input 2: Description of input 2
    //   ...
    //
    // Process:
    //  1. Key step 1
    //  2. Key step 2
    //  3. Key step 3
    //  ...
    //
    // Returns:
    //   - Return type: Description of return value
    //   ...
    </function-comment-format>
</format>

<input>
{{{ input }}}
</input>
```

### Description

I think **continue ** should provide a way to pass the user input or highlighted code into prompt

### Log output

```Shell

```

**Comment by levity0815** [comment]
I can confirm this bug. Here my info:

```
- OS: Linux, Windows
- Continue version: 1.1.26 & 1.0.6
- IDE version: VSCode 1.99.3
- Model: gpt4-o openai
- config:

name: Local Assistant
version: 1.0.0
schema: v1
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
models:
  - name: GPT-4o
    provider: openai
    model: gpt-4o
    apiKey: sk-...
prompts:
  - name: explain
    description: explain in detail
    prompt: |
      {{{input}}}
      Please read the code and explain it step by step.
```

steps to reproduce are:
- select code
- hit Ctrl+L
- type `/`
- use tab to select prompt
- use enter to run the LLM

output is:
```
It seems that there was a formatting issue, and the code you intended to share is not visible. Could you please try resending the code in a formatted way or explain which part you need help with?
```
![Image](https://github.com/user-attachments/assets/9d32c095-2c5b-472a-93b7-3d0f0f626783)
