### ISSUE TITLE
trying to use deepseek with VS code

### ISSUE THREAD

**Issue by geo0o91** [continuedev/continue#5391]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows 10 pro
- Continue version:
- IDE version:VScode 1.95
- Model: DeepSeek
- config:
  

  
  OR link to assistant in Continue hub:
```

### Description

I can't chat with DeepSeek

### Log output

```Shell

```

**Comment by sestinj** [comment]
@geo0o91 Can you share your `config.yaml` or `config.json` that is causing the error?

For reference, I'm currently using the following for DeepSeek and getting successful responses:

```yaml
models:
  - uses: deepseek/deepseek-chat
    with:
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
```
