### ISSUE TITLE
qwen3 support

### ISSUE THREAD

**Issue by luxixing** [continuedev/continue#5407]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

this is qwen3 release blog：https://qwenlm.github.io/zh/blog/qwen3/
qwen3 is best for mcp or tools use
i hope continue support qwen3

**Comment by ccckblaze** [comment]
wait for update

**Comment by TyDunn** [comment]
From Discord

> there seems to be some issues with Qwen3 out of the box, looking at the github issues. for one, the reasoning is not displayed at all. I activated the reasoning parser in vllm, which means that the reasoning content is in the completion.choices[0].message.reasoning_content of the response? IIRC these kind of "features" in the UI were handled by checking the model name often (e.g. looking for "anthropic", "r1" or "o1" in the model name?) I couldn't find a setting in the config yaml to explicitly mark it as a reasoning model. maybe there's an easy hotfix?

**Comment by TyDunn** [comment]
It looks like it works with both thinking and no_think via Ollama: https://hub.continue.dev/ollama/qwen3-14b

What model runners are you using? The one on Discord was using vLLM

**Comment by antony66** [comment]
There certainly is an issue with qwen3 support. I am using ollama and qwen3:32b model. I tried ollama on mac os (m4 with 128 Gb unified ram) and linux (2 x A100 80 Gb). In both cases reasoning just stops after a certain time, like 2.5 minutes. No errors on ollama side (OLLAMA_DEBUG=1). The same prompt is working fine via Page Assist browser plugin. Moreover, the same prompt via CLINE is also working fine. Which makes me think this is continue.dev issue.

**Comment by metcalfc** [comment]
I've confirmed that Qwen3 works with Ollama and Continue. I tried the 4B and 30B models. Thinking and `no_think` work in Continue.

```
name: Qwen3 via Ollama
version: 1.0.0
schema: v1
models:
  - uses: ollama/qwen3-30b
    override:
      roles:
        - edit
        - chat
        - apply
        - autocomplete
  - uses: ollama/nomic-embed-text-latest
context:
  - uses: continuedev/diff-context
  - uses: continuedev/codebase-context
  - uses: continuedev/url-context
  - uses: continuedev/folder-context
  - uses: continuedev/terminal-context
  - uses: continuedev/code-context
  - uses: continuedev/file-context
```

**Comment by NGC13009** [comment]
At present, the qwen3 running on ollama will be prompted that it cannot set the autocomplete promptTemplates, but in reality, it seems to be possible to set them, and the continue plugin has not reported any errors. I think this may be a bug in the configuration file rules.

![Image](https://github.com/user-attachments/assets/cf9a52b0-1f01-4c29-b36a-55b4bba00ee0)

In addition, currently continue still does not support the switch to set the thinking mode for qwen3 running on ollama. I can only manually turn on or off thinking using the `/notlink ` prompt.

Hope to further increase support, including:
1. When chatting, it is more convenient to turn on or off the QWEN3 series of thinking (or is there a better way? It can support a configuration option for the model. When it is true, the thinking mode switch is forcibly displayed to be compatible with any possible model name)
2. Autocomplete can be configured to turn off thinking mode (I am currently using a custom prompt implementation, but I hope there is a better implementation effect), and it is also compatible with automatically ignoring the '<think>' tag when turning off thinking mode.
3. Increase compatibility with the Alibaba Bailian platform API. Currently, continue is still not compatible with the Alibaba API's thinking model to display the thinking chain function, which appears to be stuck during loading and does not display the thinking process. Tracking: [# 5037](https://github.com/continuedev/continue/issues/5037)

At present, qwen3:4b is a model that is very suitable for running on small graphics cards (<8GB), and after experiencing it, it is very suitable as an autocomplete code model and chat model. I hope to optimize the experience for qwen3 as soon as possible, which will be very helpful  : )

**Comment by antony66** [comment]
How do you guys set it to no_think mode?

**Comment by NGC13009** [comment]
@joakimriedel 
```yaml
  - name: qwen3:4b-16k - ollama
    provider: ollama
    model: qwen3:4b-16k # usermodel: 16k ctx size
    apiBase: http://127.0.0.1:11434/
    roles:
      - chat
      - edit
      - autocomplete
      - apply
      - summarize
    promptTemplates:
      autocomplete: |
        `
        按照给出的文本前后缀，直接给出猜测的补全片段。<|fim_prefix|>{{{prefix}}}<|fim_suffix|>{{{suffix}}}<|fim_middle|>当前文件名称：{{{filename}}}, 项目名称：{{{reponame}}}/nothink
        `  # chinese prompt meaning: Provide a guessing completion fragment directly based on the given text prefix and suffix. .... current file name ....... project name ........
    requestOptions:
      verifySsl: false
```

**Comment by hr0109** [comment]
> [@joakimriedel](https://github.com/joakimriedel)
> 
>   - name: qwen3:4b-16k - ollama
>     provider: ollama
>     model: qwen3:4b-16k # usermodel: 16k ctx size
>     apiBase: http://127.0.0.1:11434/
>     roles:
>       - chat
>       - edit
>       - autocomplete
>       - apply
>       - summarize
>     promptTemplates:
>       autocomplete: |
>         `
>         按照给出的文本前后缀，直接给出猜测的补全片段。<|fim_prefix|>{{{prefix}}}<|fim_suffix|>{{{suffix}}}<|fim_middle|>当前文件名称：{{{filename}}}, 项目名称：{{{reponame}}}/nothink
>         `  # chinese prompt meaning: Provide a guessing completion fragment directly based on the given text prefix and suffix. .... current file name ....... project name ........
>     requestOptions:
>       verifySsl: false

@NGC13009 我用ollama官方的qwen3:4b模型+您贴出来配置文件+vscode商店的最新版continue。可以正常聊天，但是自动补全结果永远是\<\/think\>。您可以提供您用的模型出来给我们参考下吗？感谢！

**Comment by NGC13009** [comment]
@hr0109 有时候就是会这样，有时候就好了。我现在把自动补全已经切换为qwen2.5了。这个问题只能等待continue官方修复了。

**Comment by NGC13009** [comment]
@hr0109 Regarding the issue with the autocomplete function for qwen3, I tried to fix it, and it's working fine on my local machine now. All that's left is to wait for this PR to be merged, after which it should work normally.
PR: #6594 
Related issues: #5709

**Comment by kevin-pw** [comment]
> In both cases reasoning just stops after a certain time, like 2.5 minutes.

Incomplete responses are often caused by the `max_tokens` parameter that defaults to 4096 tokens in continue. Thinking models usually generate more tokens than non-thinking models for the same input prompt, so the default value of 4096 chosen in continue is somewhat low. 

To fix incomplete responses, try setting `max_tokens` to a higher value like 16000 or so in your `config.yaml`:
```yaml
models:
  - name: mymodelname
    model: mymodel
    defaultCompletionOptions:
      contextLength: 131072
      maxTokens: 16000
```
Note that this approach will then reduce your input prompt context window by 16000 tokens, so it helps to also set the parameter `contextLength` to the maximum model-specific context window to give your input prompts as much space as possible.
