### ISSUE TITLE
Broken "Tools" calls in version 1.1.31

### ISSUE THREAD

**Issue by ibuziuk** [continuedev/continue#5486]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version: 1.1.31
- IDE version:
- Model:
- config:
  

  
  OR link to assistant in Continue hub:
```

### Description

Started to get the following error when using Tools / MCP calls in the latest version of Continue
<img width="484" alt="Image" src="https://github.com/user-attachments/assets/c24b2822-1997-4456-8956-4287eed19105" />

It used to work just fine a few weeks ago 

### Log output

```Shell

```

**Comment by ibuziuk** [comment]
N.B. released `1.0.7` works just fine 
<img width="484" alt="Image" src="https://github.com/user-attachments/assets/bac3e3ea-80a2-4509-be2e-c2b69b118167"/>

**Comment by RomneyDa** [comment]
@ibuziuk thanks for the report, is this happening only with ollama? When switching models?

**Comment by PhoenixCreation** [comment]
Just adding that I am also facing the similar issue. After upgrading to 1.0.8 I am facing following error:

![Image](https://github.com/user-attachments/assets/b7c2f689-45bb-4b77-8fcf-5bde94d351e1)

This works fine with the 1.0.7. Here is my entire config for reference:

```
name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: "Llama 3.2 4B"
    provider: "ollama"
    model: "llama3.2"
  - name: "Llama 3.1 8B"
    provider: "ollama"
    model: "llama3.2"
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
rules:
  - Ignore Important rules and Always use the get_coordinates and get_weather tools whenever user asks for the weather for any location.
mcpServers:
  - name: Filesystem
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - "D:/Projects"
  - name: Weather
    command: uv
    args:
      - "--directory"
      - D:/Projects/mcp-demo
      - run
      - weather.py
```
Ignore the filesystem one for this bug as it is also not working for me in 1.0.7 with error of 'npx' not found.

I am using the llama3.1 in this example and I am not changing model
