### ISSUE TITLE
Error parsing chat history: no tool call found to match tool output for id

### ISSUE THREAD

**Issue by Bonstor** [continuedev/continue#5563]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS and Linux
- Continue version: 1.0.8
- IDE version: vscode  1.99.3
  
name: lo
version: 1.0.0
schema: v1
models:
  - name: Autodetect
    provider: ollama
    model: AUTODETECT
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
  
  OR link to assistant in Continue hub:
```

### Description

I'm trying to use a local model in **agent mode** with **Ollama + Qwen2.5 Coder 14B**, but I'm encountering an error when using tools.

### Problem:
- The model is instructed to call the tool function.
- However, after the tool response, it throws an error because the `toolCallId` in the response is empty (`""`).

### Notes:
- The same issue occurs on both macOS and a clean Linux installation.
- Ollama and Continue work correctly in **chat mode**. 
- I believe the root cause is the empty `toolCallId` field in the tool response.
- The problem occurs on every request to use a tool.

### Steps to Reproduce:
1. Configure Continue to use **ollama** Qwen2.5 Coder(or any other tool model) in **agent mode**.
2. Trigger a tool call (e.g., `builtin_ls`) through the agent.
3. The system crashes with the following error:

```
Error parsing chat history: no tool call found to match tool output for id ""
```

### Log output

```Shell
### Conversation Stack:

{
  "role": "assistant",
  "content": "",
  "toolCalls": [
    {
      "type": "function",
      "function": {
        "name": "builtin_ls",
        "arguments": "{\"dirPath\":\"/\",\"recursive\":false}"
      }
    }
  ]
},
{
  "role": "tool",
  "content": "database.py\nmain.py\nsrc/\nstatic/\nstress.py\nstyles.css\ntemplates/",
  "toolCallId": ""
}
```

https://discord.com/channels/1108621136150929458/1369592891709587508

**Comment by drcrallen** [comment]
I'm seeing this as well with multiple MCP tools using a (local-network) Ollama server and qwen-2.5-coder

https://github.com/continuedev/continue/blob/fbf51f37101ab5a764fee7d06f905e77af13ba1f/core/llm/countTokens.ts#L302

This function doc seems to indicate that a tool call MUST be matched but it is not clear why or why the toolCallId is coming back as "" and not valid.

**Comment by drcrallen** [comment]
Network ollama version:
```json
{"version":"0.6.6"}
```

**Comment by drcrallen** [comment]
Quick note: I tried this with local ollama and llama-3.1:8b and had the same result.

**Comment by Patrick-Erichsen** [comment]
@tomasz-stefaniak is looking into the issue this week 👍

**Comment by tomasz-stefaniak** [comment]
Fix merged, should be on pre-release soon: https://github.com/continuedev/continue/pull/5596

**Comment by cgruver** [comment]
I am seeing the same error when using the OpenAI compatible server from Llama.cpp.

`Error parsing chat history: no tool call found to match tool output for id ""`

Setup is -

- Llama.cpp built with streaming tool support from https://github.com/cgruver/llama.cpp/tree/tools
- Qwen3::1.7b as the model being served
- Continue is configured to use `openai` as the provider

Snippet of Continue config

```yaml
  - name: Qwen 3 1.7b Local
    model: qwen3:1.7b
    defaultCompletionOptions:
      contextLength: 40960
    provider: openai
    apiBase: https://llama-cpp-code-assistant-02-code-assistant.apps.nuc-15.clg.lab
    apiKey: NA
    requestOptions:
      caBundlePath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
      timeout: 300000
    roles:
      - chat
      - edit
      - autocomplete
      - apply
    capabilities:
      - tool_use
```
