### ISSUE TITLE
Credential should be scoped to correct service: 'execute-api'

### ISSUE THREAD

**Issue by Sagun15** [continuedev/continue#5569]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config:
  

  
  OR link to assistant in Continue hub:
```

### Description

I've created a secure proxy for our company's self-hosted LLM model running on AWS Bedrock. My architecture includes a Lambda proxy server with Cognito-based authentication, API Gateway endpoints for login and model access, and a custom token-based validation system. This works perfectly with Postman.

When configuring Continue extension in VSCode with my API Gateway endpoint, I get the following error:
```
Failed to communicate with Bedrock API: Credential should be scoped to correct service: 'execute-api'.
```

My Continue config includes:
```
- name: Secure Amazon Nova Micro
  provider: bedrock
  model: apac.amazon.nova-micro-v1:0
  apiBase: https://xyz.execute-api.ap-south-1.amazonaws.com/prod/bedrock
  apiKey: 3cdb482c-cbae-4940-8463-37917c0e74c0
  env:
    region: ap-south-1
  roles:
    - chat
```

### Log output

```Shell

```
