### ISSUE TITLE
Unable to add multiple models to ~/.continue/models/config.yaml

### ISSUE THREAD

**Issue by aarononeal** [continuedev/continue#5621]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue version: 1.1.34 pre-release
- IDE version: 1.100.0
- Model: Any Ollama
- config:
  
name: New model
version: 0.0.1
schema: v1
models:
  - provider: anthropic
    model: claude-3-7-sonnet-latest
    apiKey: test
    name: Claude 3.7 Sonnet
    roles:
      - chat
      - edit
  - name: Llama 3.1 8B
    provider: ollama
    model: llama3.1:8b
```

### Description

Adding any `ollama` provider model to `~/.continue/models/new-model.yaml` makes *all* models disappear from the model list in the Chat UI. If the `ollama` model above is removed, the `anthropic` model suddenly appears. 

It seems ollama models are only supported when added directly to an assistant/models section.

### To reproduce

Add an `ollama` model to `~/.continue/models/new-model.yaml`.

### Log output

```Shell

```

**Comment by aarononeal** [comment]
After more testing it appears that the issue is not Ollama specifically. Every model has to be placed into its own file like so:

```shell
name: gemma3:12b
version: 0.0.1
schema: v1
models:
  - name: gemma3:12b
    provider: ollama
    model: gemma3:12b
    roles:
      - chat
      - edit
      - apply  
      - autocomplete
```

I don't know if this is a bug or by design, but the [documentation page](https://docs.continue.dev/reference#models) is not clear about limitations for local blocks and shows multiple models in examples.

**Comment by 44cort44** [comment]
Here's 2 models in the same default config.yaml file:

```name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Docker qwen3:30b-a3b-q4_K_M
    provider: openai
    apiBase: http://localhost:12434/engines/v1
    model: ai/qwen3:30B-A3B-Q4_K_M
    completionOptions:
      contextLength: 41000
      maxTokens: 16384
    roles:
      - chat
      - edit
      - apply
      - summarize
    env:
      useLegacyCompletionsEndpoint: false
  - name: Ollama qwen3:30b-a3b-q4_K_M
    provider: ollama
    model: qwen3:30b-a3b-q4_K_M
    defaultCompletionOptions:
      contextLength: 41000
      maxTokens: 16384
    capabilities:
      - tool_use
    roles:
      - chat
      - edit
      - apply
      - summarize
```

so why wouldn't this work for you @aarononeal ?

```
name: gemma3
version: 0.0.1
schema: v1
models:
  - name: gemma3:12b
    provider: ollama
    model: gemma3:12b
    roles:
      - chat
      - edit
      - apply  
      - autocomplete
  - name: gemma3:27b
    provider: ollama
    model: gemma3:27b
    roles:
      - chat
      - edit
      - apply  
      - autocomplete
```
