### ISSUE TITLE
Relace instant apply failure - no support for completion

### ISSUE THREAD

**Issue by IngLP** [continuedev/continue#5644]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 15.4.1
- Continue version: 1.0.16
- IDE version: IntelliJ 2025.1.1.1
- Model:
- config:
  
models:
  - name: Relace Instant Apply
    provider: relace
    model: Instant-Apply
    apiKey: rlc-MS
    roles:
      - apply
    promptTemplates:
      apply: "{{{ new_code }}}"
  
  OR link to assistant in Continue hub:
```

### Description

Ask whatever model to do a change to your code. Apply it using Relace Instant Apply (model config from continue hub). Apply fails with error "Relace provider does not support streaming completion."

### Log output

```Shell

```

**Comment by tomasz-stefaniak** [comment]
@IngLP could you send a reproduction video? We are aware of some Relace issues but it's the first time I see one that's streaming related. A video would help me reproduce this locally.

**Comment by IngLP** [comment]
It's not a streaming problem, as far as I jave understood.
The problem is that in this file https://github.com/continuedev/continue/blob/432f36c080a50554c2a9648f4451d3d7c082aab1/packages/openai-adapters/src/apis/Relace.ts
the completionStream method is called instead of the chatCompletionStream method, and the completionStram method is not implemented.

**Comment by OlhinAS** [comment]
Hi @tomasz-stefaniak!

I have freshly installed Continue 1.0.18 for JetBrains EAP and got the same behavior when applying code block with Relace. 
My core log (no dev mode) is next:

```
[2025-05-24T22:58:37] Error: Relace provider does not support streaming completion. 
[2025-05-24T22:58:37] Error running handler for "streamDiffLines":  Error: Relace provider does not support streaming completion.
[2025-05-24T22:59:05] Error: Relace provider does not support streaming completion. 
[2025-05-24T22:59:05] Error running handler for "streamDiffLines":  Error: Relace provider does not support streaming completion.
```

**Comment by IngLP** [comment]
Hi @tomasz-stefaniak any updates on this? I am totally blocked in using Continue because I have no way to apply code changes! I tried

- gemini flash but it forgots closed square brackets
- openai mini but removes parts of my code (comments mostly) which should not be removed

I really don't know what to do!

**Comment by Patrick-Erichsen** [comment]
Could you try using the following in your config.yaml instead?

```yaml
models:
  - uses: relace/instant-apply
    with:
      RELACE_API_KEY: ${{ secrets.RELACE_API_KEY }} ## Or if ~/.continue/config.yaml, just enter the API key
```

That will use the exact config from https://hub.continue.dev/relace/instant-apply?view=config

**Comment by IngLP** [comment]
I already tried it, same error.

**Comment by hnrhn** [comment]
I can also confirm that the error is not restricted to local setups using a config.yaml file. I get the same error when trying to use Relace in JetBrains both when using local config and when using the config directly from Hub. The error message exactly matches what's found in the file mentioned in https://github.com/continuedev/continue/issues/5644#issuecomment-2899292477

**Comment by PeterSarvas** [comment]
I encountered the same error message ("Relace provider does not support streaming completion") while using the VSCode extension. 

The issue wasn't actually related to streaming support, but rather to the prompt format being sent to Relace. In my case, omitting this section from my `config.yaml`:

```yaml
promptTemplates:
  apply: "{{{ new_code }}}"
```

caused the final message sent to Relace to have a conversational ChatML structure instead of the expected format.

**Root cause:** The function `streamDiffLines` (in `core/edit/streamDiffLines.ts`) calls `constructEditPrompt`, which returns a `string`. Later, in `recursiveStream.ts` (in `core/edit/recursiveStream.ts`), when the prompt is a string, it calls `llm.streamComplete` instead of `llm.streamChat` - but Relace expects the latter.

The error message is misleading since it suggests a streaming issue when it's actually a prompt format problem.

**Comment by shaked8634** [comment]
I suffer the same issue (IntelliJ IDEA 2025.2.3).
core.log:
>[2025-10-06T20:01:20] Error: Relace provider does not support streaming completion. 
[2025-10-06T20:01:20] Error running handler for "streamDiffLines":  Error: Relace provider does not support streaming completion.

**Comment by nicoabie** [comment]
> Could you try using the following in your config.yaml instead?
> 
> models:
>   - uses: relace/instant-apply
>     with:
>       RELACE_API_KEY: ${{ secrets.RELACE_API_KEY }} ## Or if ~/.continue/config.yaml, just enter the API key
> That will use the exact config from https://hub.continue.dev/relace/instant-apply?view=config

I can confirm this instructions made it work

Now I have

```yaml
- name: Relace Instant Apply
    provider: relace
    model: Fast-Apply
    apiKey: *****
    roles:
      - apply
    promptTemplates:
      apply: "{{{ new_code }}}"
    defaultCompletionOptions:
      contextLength: 40000
      maxTokens: 32000
```

With this configuration it works


Before I had

```yaml
 - name: Relace Instant Apply
     provider: openai
     model: relace-apply-3
     apiBase: https://instantapply.endpoint.relace.run/v1
     apiKey: *****
     roles:
       - apply
```

And it would try to call /completions endpoint that relace does not offer https://docs.relace.ai/api-reference/introduction#model-endpoints
