### ISSUE TITLE
maxStopWords option in YAML config

### ISSUE THREAD

**Issue by tkulmburg-nc** [continuedev/continue#5663]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version: 1.0.9
- IDE version:VSCode 1.99.3
```

### Description

Hi,
I encountered an issue where I got autocompletion to work with the deprecated JSON config, but not with the new YAML one.
We are accessing different models through litellm (openai api), the concrete problem occured with gemini 2.0 flash, that only allows 1 to 6 stop sequences.
I am using the following config:
```
models:
  - name: Gemini 2.0 Flash
    model: gemini-2.0-flash
    provider: openai
    apiBase: https://xxx
    apiKey: xxx
    env:
      useLegacyCompletionsEndpoint: false
    roles:
      - autocomplete
```

The issue is that I always get the following error:
```
Error generating autocompletion:  Error: Malformed JSON sent from server: {"error": {"message": "litellm.BadRequestError: VertexAIException BadRequestError - b'{\\n  \"error\": {\\n    \"code\": 400,\\n    \"message\": \"Unable to submit request because it has a stopSequences value of 10 but the supported range is from 1 (inclusive) to 6 (exclusive). Update the value and try again.\",\\n    \"status\": \"INVALID_ARGUMENT\"\\n  }\\n}\\n'", "type": null, "param": null, "code": "400"}}
```

However, with the old JSON config i got it to work using `"maxStopWords": 5,`, but this option is not existing anymore according to the yaml reference.

It is also not mentioned in the migration guide, as well es not in the "Deprecated configuration options", so im wondering whats the correct way of handling this now?

Thanks!

### Log output

```Shell

```
