### ISSUE TITLE
Support referencing external Markdown files in rule definitions

### ISSUE THREAD

**Issue by azu-kazu** [continuedev/continue#5666]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Writing implementation guidelines directly inside YAML has two drawbacks.
First, it forces us to embed Markdown in a YAML block, which hurts readability.
Second, when another AI tool—such as a code-review assistant—needs to pull the same guidelines from a Markdown file, we have to duplicate the content in both places, violating the DRY principle.

### Solution

Provide a way for YAML to import external Markdown:

```yaml
name: New rule
version: 0.0.1
schema: v1
rules:
  - name: XXX Guidelines
    markdown: ./docs/xxx-guidelines.md
```
