### ISSUE TITLE
[Feature Request] Add Thinking Mode Toggle and Filter `<think>`

### ISSUE THREAD

**Issue by NGC13009** [continuedev/continue#5709]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Qwen3, like Claude, supports enabling or disabling the thinking mode at any time, and it is a model that can be deployed locally via Ollama. However, continue still has not provided a convenient option to enable or disable thinking at any time. Users still need to manually input `/nothink` to control the model, which is very inconvenient. It is hoped that continue will provide a convenient switch to control the model's thinking mode when calling Ollama for local execution.

In addition, I want to configure qwen3 as an autocomplete model, but the current continue's autocomplete does not filter the `<think>` tag. Even when the thinking mode is turned off, ollama will return an empty `<think>` tag, and continue will include them in the response, filling them into the code, making autocomplete unavailable.

This issue also appears in the problem of automatically generating titles.

![Image](https://github.com/user-attachments/assets/03ca8488-9786-40b8-8bf4-9c90d7aceb61)

### Solution

In summary, three issues are reflected here:
1. A quick toggle switch for switching models provided by ollama is needed.
2. The switchable model is currently not properly configured as an autocomplete model.
3. The current model cannot generate the title and abstract correctly.

**Comment by NGC13009** [comment]
@tomasz-stefaniak I have tried these settings, but they cannot resolve the problems I encountered.

I would like to add a thinking toggle button, but for now I have to default to disabling thinking by adding `/nothink` to the system prompt, and enable thinking by using `/think`. This method works, but it's not convenient.

Moreover, it completely fails to address the issue of outputting the `</think>` tag when using autocomplete. This can only be resolved by hoping that the continue plugin will filter out this suggestion (i.e., the initial pair of `<think>` tags that the model produces at the beginning), while not filtering out subsequent tags, as those might be part of the normal output.

The current version (v1.0.7) still cannot correctly retrieve the title from the history using thinking-type models.

**Comment by wenyifancc** [comment]
> [@NGC13009](https://github.com/NGC13009) does the `reasoning` setting at least partially fix the issues you're having?
> 
> https://docs.continue.dev/json-reference#completionoptions
Even changing reasoning to false cannot make the auto-completion feature available in the Qwen3 series models, because Qwen3 models will still return an empty think tag even when thinking is disabled.
Here is an example of an actual return:
`
<think>

</think>

params.add("options","1);
`
From the above example, it can be seen that to make the auto-complete function available, the think tags and blank lines (the first four lines) need to be filtered out when reasoning is set to false. Content starting from the fifth line is what is needed.
Or provide an extensible interface that allows users to further customize and filter the information returned by the model, thereby enhancing its versatility.

**Comment by FelikZ** [comment]
Ollama since 0.9.0 [supports "think" option](https://github.com/ollama/ollama/releases/tag/v0.9.0-rc0) both to API's and CLI. Would be nice to get this supported in YAML config to passthrough. @tomasz-stefaniak

**Comment by defaultsecurity** [comment]
Yes, please allow us to leverage ollama's new think option.

**Comment by nikiosna** [comment]
```
  - name: QWen 3 0.6b
    provider: ollama
    model: qwen3:0.6b
    requestOptions:
      extraBodyProperties:
        think: false
    roles:
      - autocomplete
```
This does work in the config.yaml.
(But the results for qwen3 autocomplete are bad in my experience. Best model I found is `avcodes/qwen2.5-fim`.)

**Comment by NGC13009** [comment]
@nikiosna This configuration will directly disable thinking and cannot be switched to enabled at any time when in use. At the same time, it indeed does not work properly in autocomplete.

I think a better approach would be to provide a toggle switch for the chat function to enable or disable the thinking mode of the Qwen3 series more conveniently. Currently, this could be achieved by adding a JSON field during the request process to POST ollama:11434/v1/chat/... (similar to the configuration you mentioned in YAML, but this would be an optional setting for each conversation).

At the same time, for autocomplete, a customizable regular expression can be added to filter prompts, allowing users to filter out the first occurring <input> tag pair themselves, thus enabling the model to function properly

**Comment by NGC13009** [comment]
I have submitted part of the fix code and updated the documentation. The related PR can be seen here: #6594 .

1. Added support for the autocomplete feature for the qwen3 model.
2. The documentation has been updated to guide how to configure the autocomplete feature for models with switchable toggle-like model for the thinking function.

If this code can be merged, then qwen3 will be correctly applicable to the autocomplete function. Anythings just like `</think>`  will be remove.

At the same time, you still need to configure an additional model to disable the thinking feature for faster responses. You can refer to my configuration plan:

```yaml
  - name: qwen3:14b - ollama    # This model is currently enabled for thinking by default
    provider: ollama
    model: qwen3:14b                 # for example
    apiBase: http://127.0.0.1:11434/
    capabilities: [tool_use]
    roles:                                      # do NOT add autocomplete function in which with think
      - chat
      - summarize

  - name: qwen3:14b&nothink - ollama    # Come up with a name, which without think
    provider: ollama
    model: qwen3:14b                                 # same model
    apiBase: http://127.0.0.1:11434/
    capabilities: [tool_use]
    requestOptions:
      extraBodyProperties:
        think: false                                         # turn off think ! 
    roles:
      - chat
      - autocomplete                                    # now it can be added to autocomplete function
      - edit                                                    # it can also work in EDIT.
      - apply                                                 # and APPLY
      - summarize
```

After that, set the model below to the autocomplete model to disable thinking. You can refer to my setup method:

<img width="671" height="411" alt="Image" src="https://github.com/user-attachments/assets/67ec2a76-7769-448e-a8eb-4698be3a4808" />

All these settings work properly (I have done some tests, and at least on my end, they are functioning correctly. I am using `qwen3:14b`). 
Additionally, in the chat feature, you can also quickly enable or disable thinking by selecting different models, which serves as an alternative to the thinking toggle switch.

However, the issue of generating the title is still not resolved. I have to temporarily disable the feature of generating titles through the model. (Using the first round of user input as the title is actually sufficient)

Please note that the autocomplete feature needs to wait until the current code is merged, and then the plugin needs to be updated before it can be used normally. It might take another one or two weeks.
