### ISSUE TITLE
Web search in agent mode fails every time - 1000 tokens remaining

### ISSUE THREAD

**Issue by RichardJECooke** [continuedev/continue#5753]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Xubuntu 25.04
- Continue version: 1.0.10
- IDE version: 1.100.2
- Model: Ollama Qwen3 14B /no_think
- config: I don't know what this is
  

  
  OR link to assistant in Continue hub:
```

### Description

Whenever I ask Continue in Agent mode to do a websearch, like what is bitcoin price today, I get the error below:

Not enough context available to include the system message, last user message, and tools. There must be at least 1000 tokens remaining for output. Request had the following token counts: - contextLength: 8192 - counting safety buffer: 163.84 - tools: ~906 - system message: ~352 - last user or tool + tool call message tokens: ~27543 - max output tokens: 4096

### To reproduce

Start Continue chat in Agent mode with ollama locally. Ask it any web search question about today.

### Log output

```Shell
Cannot paste, textbox says - Field can not be longer than 65536 characters
```

**Comment by xinity** [comment]
same issue here :(

**Comment by Patrick-Erichsen** [comment]
I think this is just a case of an overly confusing error. The problem is that you're using 27k tokens on the web search and that model has a default context length of 8192.

I believe qwen3 has 40k so you could set the `defaultCompletionOptions.contextLength` to `40_000`: https://docs.continue.dev/reference#models

**Comment by RichardJECooke** [comment]
Thanks. I tried this YAML, which parses in an editor, but is rejected by Continue:

```
name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: qwen8b
    provider: ollama
    model: qwen3:8b
    roles:
      - chat
      - edit
      - apply
      - agent
      - autocomplete
    defaultCompletionOptions:
      contextLength: 40000
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
```
