### ISSUE TITLE
MCP tools are showing but are not called

### ISSUE THREAD

**Issue by maximelebastard** [continuedev/continue#5771]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS
- Continue version: 1.1.32
- IDE version: 1.100.2
- Model: any
- config: 
  
%YAML 1.1
---
version: 1.0.16
schema: v1

bedrock: &bedrock
  provider: bedrock
  env:
    region: eu-central-1
    profile: bedrock

models:
  - name: (aws) Anthropic Claude 3.5 Sonnet
    <<: *bedrock
    model: anthropic.claude-3-5-sonnet-20240620-v1:0
    roles:
      - chat
      - edit
      - apply
  - name: (aws) Anthropic Claude 3.7 Sonnet
    <<: *bedrock
    model: eu.anthropic.claude-3-7-sonnet-20250219-v1:0
    roles:
      - chat
      - edit
  - name: (aws) Anthropic Claude 3 Haiku
    <<: *bedrock
    model: anthropic.claude-3-haiku-20240307-v1:0
    roles:
      - chat
      - autocomplete

  - name: (aws) Cohere Rerank
    <<: *bedrock
    model: cohere.rerank-v3-5:0
    roles:
      - rerank

  - name: (aws) Cohere Embed Multilingual
    <<: *bedrock
    model: cohere.embed-multilingual-v3
    roles:
      - embed
      
  - name: (local) Qwen 2.5 autocomplete
    provider: ollama
    model: qwen2.5-coder:3b
    roles:
      - chat

context:
  - provider: file
  - provider: code
  - provider: open
  - provider: folder
  - provider: clipboard
  - provider: diff
  - provider: terminal
  - provider: docs
  - provider: web
    params:
      n: 5
  - provider: codebase
  - provider: tree
  - provider: url

prompts:
  - name: commit
    description: Create a commit message from staged files
    prompt: "{{input}}"

docs:
  - name: Symfony
    startUrl: https://symfony.com/doc/6.4/index.html

defaultCompletionOptions:
  maxTokens: 4096


mcp servers config: 
name: Weather MCP server
version: 0.0.1
schema: v1
mcpServers:
  - name: Weather
    command: npx
    args:
      - -y
      - "@h1deya/mcp-server-weather"
    env: {}
```

### Description

When providing MCP server (here a basic weather example) and asking pretty directly the chat to use the MCP tools, tools are not called at all.

### To reproduce

1. Apply the provided MCP server configuration and make sure to use AWS Bedrock as a chat model, with an Anthropic tool-use compatible model like Sonnet 3.5
2. Make sure the MCP tools are appearing in the extension in the MCP servers tab and in the tools tab. In my case, you should have getAlert and getWeather tools
3. Start a new chat, in chat mode, and ask `Tomorrow's weather in Palo Alto?` (as suggested by the MCP server author)
4. The chat does not use or asks to use the weather tool
5. The LLM answers it doesn't know

Also, I don't know if it's normal, but tools do not appear as context providers when typing `@` into the chat.

### Log output

```Shell

```

**Comment by Patrick-Erichsen** [comment]
@maximelebastard are you in Chat mode rather than Agent by any chance? We're updating the UI to make this more clear soon, but let me know if that's the case.

**Comment by bojandjukic1** [comment]
Seeing the same thing with the following model set up
```
name: Local Assistant
version: 1.0.0
schema: v1
models:
- name: Llama 3.1 8B
  provider: ollama
  model: llama3.1:8b
  roles:
  - chat
  - edit
  - apply
- name: Qwen2.5-Coder 1.5B
  provider: ollama
  model: qwen2.5-coder:1.5b-base
  roles:
  - autocomplete
- name: Nomic Embed
  provider: ollama
  model: nomic-embed-text:latest
  roles:
  - embed
- name: Autodetect
  provider: ollama
  model: AUTODETECT
context:
- provider: code
- provider: docs
- provider: diff
- provider: terminal
- provider: problems
- provider: folder
- provider: codebase

mcpServers:
  - name: My MCP Server
    command: docker
    args:
        - run
        - -i
        - --rm
        - --mount
        - "type=bind,src=C:/tmp/scoped-folder,dst=/projects"        
        - mcp/filesystem
        -  /projects
```
The docs indicate that MCP servers should show up in the @ context menu but they do not, even though the servers list as healthy and running (green icon) and the tool use is populated to reflect the MCP server capabilities. 

Any guidance of whether this is simple a model limitation of the model I'm using would be appreciated.
