### ISSUE TITLE
File exceeds context length Claude 4 but not Claude 3.7

### ISSUE THREAD

**Issue by sbalk** [continuedev/continue#5861]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 15.5
- Continue version: 1.0.10
- IDE version: VSCode 1.100.2
- Model: Claude Sonnet 4.0
- config:
  
  - name: Claude 4.0 Sonnet no context
    provider: anthropic
    model: claude-sonnet-4-20250514
    apiKey: same_key1
  - name: Claude 4.0 Sonnet with context
    provider: anthropic
    model: claude-sonnet-4-20250514
    apiKey: same_key1
    defaultCompletionOptions:
     contextLength: 100000
  - name: Claude 3.7 Sonnet
    provider: anthropic
    model: claude-3-7-sonnet-latest
    apiKey: same_key1
```

### Description

I have nearly identical config files set up for claude 3.7 and 4.0 but 4.0 gives a vscode popup saying 'File exceeds context lenght'. 3.7 works fine. This happens on two computers (both macOS and vscode).

### To reproduce

1. save config.yaml:
  ```yaml
  - name: Claude 4.0 Sonnet no context
    provider: anthropic
    model: claude-sonnet-4-20250514
    apiKey: same_key1
  - name: Claude 4.0 Sonnet with context
    provider: anthropic
    model: claude-sonnet-4-20250514
    apiKey: same_key1
    defaultCompletionOptions:
     contextLength: 100000
  - name: Claude 3.7 Sonnet
    provider: anthropic
    model: claude-3-7-sonnet-latest
    apiKey: same_key1
  ```
2. Select `Claude 4.0 Sonnet no context` or `Claude 4.0 Sonnet with context` in 'Select Model' dropdown.
3. Add any file (as small as bytes)
4. Get popup

### Log output

```Shell
No console logs are generated by this action.
```
