### ISSUE TITLE
Allow Renaming "Local Assistant" Label in VS Code Chat UI

### ISSUE THREAD

**Issue by LeMajaw** [continuedev/continue#5862]
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

## Feature Request:
Currently, the Continue VS Code extension displays the label "Local Assistant" in the UI when using a local model (e.g., via Ollama), even if the model is given a custom name like Deepseek in the config.yaml.

This behavior creates confusion when using multiple assistants, especially when switching profiles or customizing them for specific tasks.
Even when everything else in the config updates (model name, prompts, rules), the visible assistant label stays generic as "Local Assistant", which doesn't reflect the user's intended setup.

💡 A custom editable label with free free typing (like "Deepseek" or even "My Own Deepseek") would improve clarity, especially in professional or multi-profile environments.

### Solution

Allow overriding the **assistant name label** in the Continue UI via the `config.yaml` model block.

For example:

```yaml
models:
  - name: My Own Deepseek
    provider: ollama
    model: deepseek-coder:6.7b
    displayName: My Deepseek

**Comment by tomasz-stefaniak** [comment]
Could you share a screenshot, and also maybe share your complete config.yaml? I think the confusion here is coming from the fact that the assistant toggle and the model toggle are separate things, see screenshot:

![Image](https://github.com/user-attachments/assets/ec134571-9973-4c12-8dc1-c879592f0246)

**Comment by travis-fm** [comment]
@tomasz-stefaniak @0x23d11 I just tried doing the same thing. Even when renaming the (what I assume is) assistant name in config.yaml, the extension isn't reflecting that.

What I see:

<img width="622" height="184" alt="Image" src="https://github.com/user-attachments/assets/de11f7f4-5115-499b-b59f-f2ccb84004e7" />

My config.yaml:
```yaml
name: Mistral
version: 1.0.0
schema: v1
models:
  - name: Devstral
    model: devstral-medium-latest
    provider: mistral
    apiKey: [REDACTED]
    roles:
      - chat
      - edit
      - apply
      - summarize
    capabilities:
      - tool_use
    defaultCompletionOptions:
      contextLength: 131072
  - name: Codestral
    provider: mistral
    model: codestral-latest
    apiKey: [REDACTED]
    roles:
      - autocomplete
    defaultCompletionOptions:
      contextLength: 262144
  - name: Codestral (Embed)
    provider: mistral
    model: codestral-embed
    apiKey: [REDACTED]
    roles:
      - embed
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
```

Based on the main name field on line 1 in my config.yaml, I'd expect "Local Assistant" assistant name in the upper left to be renamed to "Mistral" in the UI, but I'm not seeing that on my end. I'm guessing that the profile/assistant feature was mainly built around the Continue Hub, but it would be nice to have multiple profiles that you can define locally, that have your different models pre-set for chat, autocomplete, etc.

I'm also pretty new to Continue still so maybe this is something that's already solved lol
