### ISSUE TITLE
token error

### ISSUE THREAD

**Issue by lishuqi1a** [continuedev/continue#5899]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config:
  

  
  OR link to assistant in Continue hub:
```

### Description

Not enough context available to include the system message, last user message, and tools. There must be at least 1000 tokens remaining for output. Request had the following token counts: - contextLength: 8192 - counting safety buffer: 163.84 - tools: ~0 - system message: ~412 - last user or tool + tool call message tokens: ~7417 - max output tokens: 4096

### To reproduce

llvm project and other project cannot analysis together

### Log output

```Shell

```

**Comment by gaby** [comment]
I'm getting this error all the time when using Devstral in Agent mode. Even thought my server (vLLM) is setup with 128,000 context window.

Setting contextWindow in continue config makes no difference.

**Comment by gaby** [comment]
@tomasz-stefaniak @lishuqi1a Any workaround for this issue?

I'm unable to use Agent mode with `Mistral/Devstral` 60-80% of the time. It just randomly fails with this error.

**Comment by jeepshop** [comment]
I had a very similar problem, and maybe yours is the same. Turns out there are two settings in the model file that effect Devstral's context window.

_contextLength_ relates to max context allowed by Devstral, and _maxTokens_ relates to the max return tokens. So in the case of Devstral I changed my YAML config to the below and it solved my issues with >1000 line files being added to context.

I believe if you don't explicitly set these, the defaults are closer to 2048 and 1024.

```YAML
  - name: Darkstar Devstral
    provider: ollama
    model: devstral:24b-small-2505-q8_0
    apiBase: http://darkstar:11434
    roles:
      - summarize
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      stream: true
      temperature: 0.15
      contextLength: 80000
      maxTokens: 40000
      keepAlive: 5
```

So in the above, the amount of tokens I can SEND to Devstral is: 80000 - 40000 = 40000
