### ISSUE TITLE
config.yaml: `uses:` with relative path doesn't work

### ISSUE THREAD

**Issue by owtaylor** [continuedev/continue#5943]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Linux (and others?)
- Continue version:git main and 1.1.41
```

### Description

Relative urls to blocks to include with `uses:` don't work, because it's trying to resolve against an absolute path to config.yaml, but stripping off the leading /.

As I read it, the call to getCleanUriPath() in:

https://github.com/continuedev/continue/blob/ceb2e5256032516919ae8f49b26bee2b8abdb194/core/config/yaml/loadYaml.ts#L113

is unnecessary and harmful.

### To reproduce

A 'uses:' statement with a relative path

``` yaml
[...]
models:
  - uses: ./include/myModel.yaml
```

Gives "Assistant includes blocks that don't exist" - debugging shows that it is trying to load `var/home/otaylor/.continue/include/myModel.yaml` with the missing initial `/`. An explicit:

``` yaml
[...]
models:
  - uses: file:///var/home/otaylor/.continue/include/myModel.yaml
```

works fine.

### Log output

```Shell

```
