### ISSUE TITLE
Failed to Configure Chutes.ai as a Custom OpenAI Provider

### ISSUE THREAD

**Issue by Stavros-alt** [continuedev/continue#6128]
### Before submitting your bug report

- [x] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue version: 1.0.13
- IDE version: 
- Model: 
- config:
  

  
  OR link to assistant in Continue hub:
```

### Description

Hello,

I'm trying to add a free model from `chutes.ai` as a custom provider in `Continue` on Windows, but I'm consistently running into a "Model/deployment not found" error. I have confirmed my local Ollama models work perfectly.

**My Goal:**
Add the `deepseek-ai/DeepSeek-V3-0324` model from Chutes.ai to my `models` list.

**My API Key:**
My key starts with `cpk_7663...` and I have confirmed it's correct.

**Configurations I Have Tried:**

I have tried multiple variations in my `config.yaml` based on standard assumptions, and all of them have failed with the same error. Here are the blocks I've tested:

*Attempt 1 (Full Model Name):*
```yaml
- name: Chutes DeepSeek V3
  provider: openai
  model: deepseek-ai/DeepSeek-V3-0324
  apiBase: https://llm.chutes.ai
  apiKey: <MY_API_KEY>
```

*Attempt 2 (Simplified Model Name):*
```yaml
- name: Chutes DeepSeek V3
  provider: openai
  model: DeepSeek-V3-0324
  apiBase: https://llm.chutes.ai
  apiKey: <MY_API_KEY>
```

*Attempt 3 (Model as Endpoint Path):*
```yaml
- name: Chutes DeepSeek V3
  provider: openai
  model: /v1/chat/completions
  apiBase: https://llm.chutes.ai
  apiKey: <MY_API_KEY>
```

**The Error:**
In all cases, I receive the error:
`Error handling model response: Likely causes: InvalidapiBase: https://llm.chutes.ai/ Model/deployment not found for: <model_name_here>`

Could you please provide the correct `config.yaml` structure for using a model from `chutes.ai`? It seems to have a non-standard configuration.

Thank you!

### Log output

```Shell

```

**Comment by Ameterius** [comment]
try this, it's worked for me
``` yaml
models:
  - name: Chutes DeepSeek V3
    provider: openai
    model: deepseek-ai/DeepSeek-V3-0324
    apiBase: https://llm.chutes.ai/v1/chat/completions#
    apiKey: <KEY>
```
