### ISSUE TITLE
Tools stopped working and only respond with json

### ISSUE THREAD

**Issue by steve-fraser** [continuedev/continue#6178]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue version:
- IDE version:
- Model:
- config:
  
name: Local Assistant
version: 1.0.0
schema: v1
mcpServers:
  - name: castai
    command: /home/coder/.nvm/versions/node/v18.20.8/bin/node
    args:
    - /workspaces/codespace/steve-fraser/castai-mcp-server/src/index.js
models:
  - name: Autodetect
    provider: ollama
    model: AUTODETECT
    apiBase: http://192.168.1.59:11434
    defaultCompletionOptions:
      temperature: 0.7
      maxTokens: 20000
      contextLength: 40960
    extraBodyProperties:
      headers:
        keep_alive: 4h
    # defaultCompletionOptions:
    #   contextLength: 40960
    #   maxTokens: 32768
    capabilities:
      - tool_use
  - name: qwen2.5-coder:32b
    provider: ollama
    model: qwen2.5-coder:32b
    apiBase: http://192.168.1.59:11434
    roles:
      - autocomplete
    requestOptions:
      extraBodyProperties:
        keep_alive: 4h
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
```

### Description

Agent mode seems to only want to generate json for the action and not execute it

### To reproduce

1. use one of the actions
Agent Mode
```
search web for docs for cast ai
```

```
{"name": "builtin_search_web", "arguments": {"query": "cast ai documentation"}}
```

![Image](https://github.com/user-attachments/assets/cf581567-387e-4c1a-9e4f-2b7d24fc5763)

### Log output

```Shell

```

**Comment by neo-rooney** [comment]
I have the same issue. With qwen2.5-coder:7b, the response is in JSON format, as shown in the image below.

![Image](https://github.com/user-attachments/assets/fe2e3f15-3f20-4bf5-87f6-bb17b8e631e6)

However, qwen3:8b shows a toggle button and neither executes the tool nor provides a text response.
![Image](https://github.com/user-attachments/assets/184f39a9-986e-4b80-8ed9-45dd0ca9b709)


I'd like to know if this is an LLM issue or a continue issue.

**Comment by steve-fraser** [comment]
Yeah this is a problem with ``` qwen2.5-coder:7b``` for me as well

**Comment by steve-fraser** [comment]
Seems to be an issue with new versions Ollama @neo-rooney 

Downgrade to [v0.7.1](https://github.com/ollama/ollama/releases/tag/v0.7.1)

**Comment by ghdoergeloh** [comment]
I have the same issue.

I compared ollama and lmstudio (same model, same config, same prompt "list all files in directory ."):

```yaml
models:
  - name: qwen2.5-coder 1.5b
    provider: ollama
    model: qwen2.5-coder:1.5b
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    capabilities:
      - tool_use
    defaultCompletionOptions:
      contextLength: 32768
      maxTokens: 8192

  - name: qwen2.5-coder 1.5b lmstudio
    provider: lmstudio
    model: qwen2.5-coder:1.5b
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    capabilities:
      - tool_use
    defaultCompletionOptions:
      contextLength: 32768
      maxTokens: 8192
```

lmstudio executed the toolcalls correctly.

ollama failed.

ollama version is 0.9.2
