### ISSUE TITLE
MCP error -32601: Method not found when using @jetbrains/mcp-proxy with Continue plugin in IntelliJ

### ISSUE THREAD

**Issue by Akazuods** [continuedev/continue#6226]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
OS: Ubuntu 24.04.2 LTS
Node: v22.16.0 (via NVM)
IntelliJ: IntelliJ IDEA 2025.1.2 (Community Edition)
Continue Plugin: 1.0.21
```

### Description

I'm trying to configure @jetbrains/mcp-proxy as an MCP server for the Continue plugin inside IntelliJ, but I keep getting the following error:

MCP error -32601: Method not found
What I've tried:

Using absolute path to npx

Running via node and npx-cli.js directly

Setting environment variables (PATH, NODE_PATH, IDE_PORT)

Verifying that the proxy runs manually (npx -y @jetbrains/mcp-proxy)

Updating both the plugin and IntelliJ

Despite all of this, the error persists. It seems like the Continue plugin can't properly communicate with the MCP proxy.

Config MCP:

name: New mcpServer
version: 0.0.1
schema: v1
mcpServers:
  - name: JetBrains
    command: npx
    args:
      - "@jetbrains/mcp-proxy"
      - "-y"
    env: {}

### To reproduce

![Image](https://github.com/user-attachments/assets/3b9860c2-cc26-4c3b-990c-e740ccb2a1bb)

### Log output

```Shell

```

**Comment by tomasz-stefaniak** [comment]
Does this bug happen when using MCP servers hosted on the hub, or when you copy an existing MCP server config from the hub and set it up locally?

**Comment by eslamo** [comment]
same issue here for all local mcp and nothing works

<img width="261" height="62" alt="Image" src="https://github.com/user-attachments/assets/e2068b43-6a2d-49ec-b31f-2b1f6b208f5e" />

```
mcpServers:
  - name: Code Reasoning
    command: npx
    args:
      - -y
      - "@mettamatt/code-reasoning"
  - name: Jetbrains MCP
    command: npx
    args:
      - -y
      - "@jetbrains/mcp-proxy"
  - name: Docs
    type: sse
    url: http://localhost:6280/sse
```
