### ISSUE TITLE
Docker MCP not working

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#6284]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
macOS: Sequoia 15.4.1
VSCode version: 1.101.1
Continue extension version: 1.0.14


name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Ollama
    provider: ollama
    model: AUTODETECT
    apiBase: http://localhost:11434
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
mcpServers:
  - name: MCP_DOCKER
    command: docker
    args:
      - mcp
      - gateway
      - run
```

### Description

https://discord.com/channels/1108621136150929458/1385559180685086780

Hi,
today I wanted to test Docker Desktop's MCP Toolkit in combination with Continue. I connected Continue in my VSCode with Docker and installed two sample MCP servers.
Continue recognizes the new MCP server in the config.yaml as MCP_DOCKER. But in the MCP tab, it shows the error:

Failed to connect to "MCP_DOCKER" Error: MCP error -32000:
Connection closed Process output: STDERR: reading registry: reading registry.yaml: SHOME is not defined

I don't know where to fix that. The sample MCP servers I took (DuckDuckGo and Fetch (Reference)) have no configuration options in Docker.
When I tested this setup, but with Claude instead of Continue, it instantly worked, so my guess is that I missed some configuration in Continue, but what?

Thanks for the help!

### Log output

```Shell

```

**Comment by Lucidpaper** [comment]
mcpServers: 
  - name: MCP_DOCKER
    command: docker 
    args: 
      - run 
      - -i 
      - --rm 
      - alpine/socat 
      - STDIO 
      - TCP:host.docker.internal:8811

worked for me instead of 

mcpServers:
  - name: MCP_DOCKER
    command: docker
    args:
      - mcp
      - gateway
      - run

**Comment by abbrechen** [comment]
@Lucidpaper Thanks for your alternative. It solved the undefined $HOME error.
I was wondering why you have used port 8811 instead of the 11434. I tried both and with the default port, on which my ollama is running on, the number of errors has been reduced to one: `Failed to connect to "MCP_DOCKER" Error: MCP error -32000`. Google says that this error is known for a wrong protocol when connecting a MCP client to a server. Turns out, my ollama just has a REST API, but no special one for MCP servers.

In the next days, I will try to find a way of running an ollama-mcp server in Docker. One option could be this npm package: https://github.com/rawveg/ollama-mcp

But overall, seems to be an ollama problem, but a Continue.dev problem.

**Comment by mkschl** [comment]
I just added this to the default config:

```yaml
env: {
      HOME: "/Users/<your user folder>"
}
```

~~It works for Docker MCP servers that do not have a configuration like connection string or access tokens~~

**Comment by HankLeo** [comment]
Thanks @mkschl , it works to me by adding ENV $HOME in the `~/.continue/config.yaml`
```yaml
mcpServers:
  - name: Docker MCP
    command: docker
    args:
      - "mcp"
      - "gateway"
      - "run"
    env: {
      HOME: "/Users/xxx" # Replace with your home directory
    }
```

**Comment by abbrechen** [comment]
@mkschl Thanks! Defining HOME solved all the problems. All MCP server could be founded.

![Image](https://github.com/user-attachments/assets/1e2e0387-d7a4-4016-9be0-9e79ae51d650)

My config looks like the one from @HankLeo  - the standard MCP server config that has been added by Docker Desktop + the environment adjustment.
But why is it solving it? What happens under the hood that the user path is crucial? And if that config snippet is needed, Docker Desktop should add it automatically.

**Comment by mkschl** [comment]
The issue is  `continue` starts a subprocess and the environment variables from the parent process seem not be shared to it. This issue has nothing to do with Docker Desktop:). But the docker command needs to have access to its `~/.docker/mcp/` folder, where all the configuration are stored

**Comment by Patrick-Erichsen** [comment]
@mkschl I think that was resolved with #6157 

This is still an issue for folks on latest release?

**Comment by ramkumarar** [comment]
Tried this in windows (with WSL running dockers) with both intellij and vscode.  Faced following error. I can run  docker run mcp from windows command line and it works fine but plugin gives the error

Failed to connect to "MCP_DOCKER" Error: MCP error -32000: Connection closed Process
output: STDERR: docker: unknown command: docker mcp Run 'docker --help' for more
information

My configuration:
```yaml
mcpServers:
  - name: MCP_DOCKER
    command: docker
    args:
      - mcp
      - gateway
      - run
    env:
      HOME: "C:\\Users\\<username>"

**Comment by thepirateclub** [comment]
@ramkumarar 
> Tried this in windows (with WSL running dockers) with both intellij and vscode. Faced following error. I can run docker run mcp from windows command line and it works fine but plugin gives the error

> Failed to connect to "MCP_DOCKER" Error: MCP error -32000: Connection closed Process
output: STDERR: docker: unknown command: docker mcp Run 'docker --help' for more
information

**(for windows)**

I'm found a solution to this problem. The problem was linked to docker-cli and its environment variables. - https://github.com/docker/cli/issues/6145.

This problem was solved by adding these lines to the **env** section:
```yaml
env: {
      "HOME": "C:\\Users\\<your user>",
      "PROGRAMFILES": "C:\\Program Files",
      "ProgramData": "C:\\Program Files",
    }
```

**Comment by jtabox** [comment]
> env: {
>       "HOME": "C:\\Users\\<your user>",
>       "PROGRAMFILES": "C:\\Program Files",
>       "ProgramData": "C:\\Program Files",
>     }

Shouldn't the **ProgramData** key actually have `ProgramData` (`C:\\ProgramData`) as value?

**Comment by TyroneNel** [comment]
This worked for me on vs code continue win 10

```yaml
name: MCP_DOCKER
version: 0.0.1
schema: v1
mcpServers:
  - name: MCP_DOCKER
    command: docker
    args:
      - mcp
      - gateway
      - run
    env:
      HOME: "C:\\Users\\XXX"
      PROGRAMFILES: "C:\\Program Files"
      ProgramData: "C:\\Program Files"
```
